In [2]:
# Pandas + SQL Practice Task
# ---------------------------
# You have three CSV files:
#     products.csv
#     categories.csv
#     sales.csv
# Task 1: Import CSV Files into MySQL
# Create a database named product_db.
# Create the following tables:
#     products
#     categories
#     sales
# Import all three CSV files into their respective tables.
# Verify that the data has been loaded successfully.


import pandas as pd
import mysql.connector

conn = mysql.connector.connect(
    user = 'root',
    password = 'root',
    host = '127.0.0.1',
    port = 3306,
    database = 'the_kiran_academy_db'
)

print("connection successfull")

connection successfull

In [3]:
st1 = 'select * from categories'
st2 = 'select * from products'
st3 = 'select * from sales'

categories = pd.read_sql(st1,conn)
products = pd.read_sql(st2,conn)
sales = pd.read_sql(st3,conn)

C:\Users\Admin\AppData\Local\Temp\ipykernel_26168\2221784452.py:5: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  categories = pd.read_sql(st1,conn)
C:\Users\Admin\AppData\Local\Temp\ipykernel_26168\2221784452.py:6: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  products = pd.read_sql(st2,conn)
C:\Users\Admin\AppData\Local\Temp\ipykernel_26168\2221784452.py:7: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  sales = pd.read_sql(st3,conn)

In [4]:
categories

   cat_id    category_name
0       1      Electronics
1       2         Clothing
2       3  Home Appliances
3       4            Books
4       5           Sports

In [5]:
products

    product_id     product_name  cat_id  price
0          101           Laptop       1  55000
1          102           Mobile       1  25000
2          103       Headphones       1   3000
3          104          T-Shirt       2    800
4          105            Jeans       2   1800
5          106  Washing Machine       3  28000
6          107     Refrigerator       3  35000
7          108      Python Book       4    650
8          109         SQL Book       4    500
9          110      Cricket Bat       5   2500
10         111         Football       5   1200
11         112      Smart Watch       1   7000

In [6]:
sales

    sale_id  product_id  qty   sale_date
0         1         101    2  2025-01-05
1         2         102    3  2025-01-08
2         3         103    5  2025-01-10
3         4         104   10  2025-01-12
4         5         105    8  2025-01-15
5         6         106    2  2025-01-18
6         7         107    1  2025-01-20
7         8         108   12  2025-01-22
8         9         109   15  2025-01-25
9        10         110    6  2025-02-02
10       11         111    8  2025-02-05
11       12         112    4  2025-02-08
12       13         101    1  2025-02-10
13       14         102    2  2025-02-12
14       15         103    7  2025-02-15
15       16         104   12  2025-02-18
16       17         105    5  2025-02-20
17       18         106    3  2025-02-22
18       19         107    2  2025-03-01
19       20         108   10  2025-03-03
20       21         109    8  2025-03-05
21       22         110    4  2025-03-08
22       23         111    7  2025-03-10
23       24         112    3  2025-03-12
24       25         101    2  2025-03-15
25       26         102    1  2025-03-18
26       27         103    6  2025-03-20
27       28         104    9  2025-03-22
28       29         105    4  2025-03-25
29       30         106    2  2025-03-28

In [10]:
# Task 2: Load Data from MySQL into Pandas
#     Connect Python to MySQL.
#     Read all three tables into Pandas DataFrames.
#     Display the first 5 records of each DataFrame.
#     Check the shape of each DataFrame.
print(categories.head())
print()
print(products.head())
print()
print(sales.head())

print()

print(categories.shape)
print(products.shape)
print(sales.shape)

   cat_id    category_name
0       1      Electronics
1       2         Clothing
2       3  Home Appliances
3       4            Books
4       5           Sports

   product_id product_name  cat_id  price
0         101       Laptop       1  55000
1         102       Mobile       1  25000
2         103   Headphones       1   3000
3         104      T-Shirt       2    800
4         105        Jeans       2   1800

   sale_id  product_id  qty   sale_date
0        1         101    2  2025-01-05
1        2         102    3  2025-01-08
2        3         103    5  2025-01-10
3        4         104   10  2025-01-12
4        5         105    8  2025-01-15

(5, 2)
(12, 4)
(30, 4)

In [ ]:
# Task 3: Merge DataFrames
#     Merge products and categories.
#     Merge the result with sales.
#     Create a common DataFrame named final_df.
#     Display the first 10 records of final_df.

df1 = pd.merge(products,categories,how='inner', on='cat_id')
print(df1)
print()

df2 = pd.merge(df1,sales,how='inner',on='product_id')
print(df2)
print()

final_df = df2[['product_id','product_name','price','category_name','sale_id','qty','sale_date']]

    product_id     product_name  cat_id  price    category_name
0          101           Laptop       1  55000      Electronics
1          102           Mobile       1  25000      Electronics
2          103       Headphones       1   3000      Electronics
3          104          T-Shirt       2    800         Clothing
4          105            Jeans       2   1800         Clothing
5          106  Washing Machine       3  28000  Home Appliances
6          107     Refrigerator       3  35000  Home Appliances
7          108      Python Book       4    650            Books
8          109         SQL Book       4    500            Books
9          110      Cricket Bat       5   2500           Sports
10         111         Football       5   1200           Sports
11         112      Smart Watch       1   7000      Electronics

    product_id     product_name  cat_id  price    category_name  sale_id  qty  \
0          101           Laptop       1  55000      Electronics        1    2
1          101           Laptop       1  55000      Electronics       13    1
2          101           Laptop       1  55000      Electronics       25    2
3          102           Mobile       1  25000      Electronics        2    3
4          102           Mobile       1  25000      Electronics       14    2
5          102           Mobile       1  25000      Electronics       26    1
6          103       Headphones       1   3000      Electronics        3    5
7          103       Headphones       1   3000      Electronics       15    7
8          103       Headphones       1   3000      Electronics       27    6
9          104          T-Shirt       2    800         Clothing        4   10
10         104          T-Shirt       2    800         Clothing       16   12
11         104          T-Shirt       2    800         Clothing       28    9
12         105            Jeans       2   1800         Clothing        5    8
13         105            Jeans       2   1800         Clothing       17    5
14         105            Jeans       2   1800         Clothing       29    4
15         106  Washing Machine       3  28000  Home Appliances        6    2
16         106  Washing Machine       3  28000  Home Appliances       18    3
17         106  Washing Machine       3  28000  Home Appliances       30    2
18         107     Refrigerator       3  35000  Home Appliances        7    1
19         107     Refrigerator       3  35000  Home Appliances       19    2
20         108      Python Book       4    650            Books        8   12
21         108      Python Book       4    650            Books       20   10
22         109         SQL Book       4    500            Books        9   15
23         109         SQL Book       4    500            Books       21    8
24         110      Cricket Bat       5   2500           Sports       10    6
25         110      Cricket Bat       5   2500           Sports       22    4
26         111         Football       5   1200           Sports       11    8
27         111         Football       5   1200           Sports       23    7
28         112      Smart Watch       1   7000      Electronics       12    4
29         112      Smart Watch       1   7000      Electronics       24    3

     sale_date
0   2025-01-05
1   2025-02-10
2   2025-03-15
3   2025-01-08
4   2025-02-12
5   2025-03-18
6   2025-01-10
7   2025-02-15
8   2025-03-20
9   2025-01-12
10  2025-02-18
11  2025-03-22
12  2025-01-15
13  2025-02-20
14  2025-03-25
15  2025-01-18
16  2025-02-22
17  2025-03-28
18  2025-01-20
19  2025-03-01
20  2025-01-22
21  2025-03-03
22  2025-01-25
23  2025-03-05
24  2025-02-02
25  2025-03-08
26  2025-02-05
27  2025-03-10
28  2025-02-08
29  2025-03-12

    product_id     product_name  price    category_name  sale_id  qty  \
0          101           Laptop  55000      Electronics        1    2
1          101           Laptop  55000      Electronics       13    1
2          101           Laptop  55000      Electronics       25    2
3          102           Mobile  25000      Electronics        2    3
4          102           Mobile  25000      Electronics       14    2
5          102           Mobile  25000      Electronics       26    1
6          103       Headphones   3000      Electronics        3    5
7          103       Headphones   3000      Electronics       15    7
8          103       Headphones   3000      Electronics       27    6
9          104          T-Shirt    800         Clothing        4   10
10         104          T-Shirt    800         Clothing       16   12
11         104          T-Shirt    800         Clothing       28    9
12         105            Jeans   1800         Clothing        5    8
13         105            Jeans   1800         Clothing       17    5
14         105            Jeans   1800         Clothing       29    4
15         106  Washing Machine  28000  Home Appliances        6    2
16         106  Washing Machine  28000  Home Appliances       18    3
17         106  Washing Machine  28000  Home Appliances       30    2
18         107     Refrigerator  35000  Home Appliances        7    1
19         107     Refrigerator  35000  Home Appliances       19    2
20         108      Python Book    650            Books        8   12
21         108      Python Book    650            Books       20   10
22         109         SQL Book    500            Books        9   15
23         109         SQL Book    500            Books       21    8
24         110      Cricket Bat   2500           Sports       10    6
25         110      Cricket Bat   2500           Sports       22    4
26         111         Football   1200           Sports       11    8
27         111         Football   1200           Sports       23    7
28         112      Smart Watch   7000      Electronics       12    4
29         112      Smart Watch   7000      Electronics       24    3

     sale_date
0   2025-01-05
1   2025-02-10
2   2025-03-15
3   2025-01-08
4   2025-02-12
5   2025-03-18
6   2025-01-10
7   2025-02-15
8   2025-03-20
9   2025-01-12
10  2025-02-18
11  2025-03-22
12  2025-01-15
13  2025-02-20
14  2025-03-25
15  2025-01-18
16  2025-02-22
17  2025-03-28
18  2025-01-20
19  2025-03-01
20  2025-01-22
21  2025-03-03
22  2025-01-25
23  2025-03-05
24  2025-02-02
25  2025-03-08
26  2025-02-05
27  2025-03-10
28  2025-02-08
29  2025-03-12

In [16]:
final_df

,product_id,product_name,price,category_name,sale_id,qty,sale_date
0,101,Laptop,55000,Electronics,1,2,2025-01-05
1,101,Laptop,55000,Electronics,13,1,2025-02-10
2,101,Laptop,55000,Electronics,25,2,2025-03-15
3,102,Mobile,25000,Electronics,2,3,2025-01-08
4,102,Mobile,25000,Electronics,14,2,2025-02-12
5,102,Mobile,25000,Electronics,26,1,2025-03-18
6,103,Headphones,3000,Electronics,3,5,2025-01-10
7,103,Headphones,3000,Electronics,15,7,2025-02-15
8,103,Headphones,3000,Electronics,27,6,2025-03-20
9,104,T-Shirt,800,Clothing,4,10,2025-01-12
10,104,T-Shirt,800,Clothing,16,12,2025-02-18
11,104,T-Shirt,800,Clothing,28,9,2025-03-22
12,105,Jeans,1800,Clothing,5,8,2025-01-15
13,105,Jeans,1800,Clothing,17,5,2025-02-20
14,105,Jeans,1800,Clothing,29,4,2025-03-25
15,106,Washing Machine,28000,Home Appliances,6,2,2025-01-18
16,106,Washing Machine,28000,Home Appliances,18,3,2025-02-22
17,106,Washing Machine,28000,Home Appliances,30,2,2025-03-28
18,107,Refrigerator,35000,Home Appliances,7,1,2025-01-20
19,107,Refrigerator,35000,Home Appliances,19,2,2025-03-01
20,108,Python Book,650,Books,8,12,2025-01-22
21,108,Python Book,650,Books,20,10,2025-03-03
22,109,SQL Book,500,Books,9,15,2025-01-25
23,109,SQL Book,500,Books,21,8,2025-03-05
24,110,Cricket Bat,2500,Sports,10,6,2025-02-02
25,110,Cricket Bat,2500,Sports,22,4,2025-03-08
26,111,Football,1200,Sports,11,8,2025-02-05
27,111,Football,1200,Sports,23,7,2025-03-10
28,112,Smart Watch,7000,Electronics,12,4,2025-02-08
29,112,Smart Watch,7000,Electronics,24,3,2025-03-12

In [18]:
# Task 4: Create New Column
#     Create a column named total_sales.
#     Formula:
#     total_sales = price * qty

# Display the following columns:
#     product_name
#     category_name
#     price
#     qty
#     total_sales

final_df['total_sales'] = final_df['price'] + final_df['qty']
final_df[['product_name','category_name','price','qty','total_sales']]

       product_name    category_name  price  qty  total_sales
0            Laptop      Electronics  55000    2        55002
1            Laptop      Electronics  55000    1        55001
2            Laptop      Electronics  55000    2        55002
3            Mobile      Electronics  25000    3        25003
4            Mobile      Electronics  25000    2        25002
5            Mobile      Electronics  25000    1        25001
6        Headphones      Electronics   3000    5         3005
7        Headphones      Electronics   3000    7         3007
8        Headphones      Electronics   3000    6         3006
9           T-Shirt         Clothing    800   10          810
10          T-Shirt         Clothing    800   12          812
11          T-Shirt         Clothing    800    9          809
12            Jeans         Clothing   1800    8         1808
13            Jeans         Clothing   1800    5         1805
14            Jeans         Clothing   1800    4         1804
15  Washing Machine  Home Appliances  28000    2        28002
16  Washing Machine  Home Appliances  28000    3        28003
17  Washing Machine  Home Appliances  28000    2        28002
18     Refrigerator  Home Appliances  35000    1        35001
19     Refrigerator  Home Appliances  35000    2        35002
20      Python Book            Books    650   12          662
21      Python Book            Books    650   10          660
22         SQL Book            Books    500   15          515
23         SQL Book            Books    500    8          508
24      Cricket Bat           Sports   2500    6         2506
25      Cricket Bat           Sports   2500    4         2504
26         Football           Sports   1200    8         1208
27         Football           Sports   1200    7         1207
28      Smart Watch      Electronics   7000    4         7004
29      Smart Watch      Electronics   7000    3         7003

In [22]:
# Task 5: Aggregate Functions
# Perform the following calculations:
#     Total Sales
#     Average Sales
#     Maximum Sales
#     Minimum Sales
#     Total Quantity Sold
#     Average Product Price

print(final_df['total_sales'].sum())
print(final_df['total_sales'].mean())
print(final_df['total_sales'].max())
print(final_df['total_sales'].min())
print(final_df['qty'].sum())
print(final_df['price'].mean())

434664
14488.8
55002
508
164
14483.333333333334

In [ ]:
# Task 6: Filtering
#     Display products with price greater than 10000.
#     Display records where quantity sold is greater than 5.
#     Display products from the Electronics category.
#     Display records where total_sales is greater than 50000.

print(final_df[final_df['price']>10000])

    product_id     product_name  price    category_name  sale_id  qty  \
0          101           Laptop  55000      Electronics        1    2
1          101           Laptop  55000      Electronics       13    1
2          101           Laptop  55000      Electronics       25    2
3          102           Mobile  25000      Electronics        2    3
4          102           Mobile  25000      Electronics       14    2
5          102           Mobile  25000      Electronics       26    1
15         106  Washing Machine  28000  Home Appliances        6    2
16         106  Washing Machine  28000  Home Appliances       18    3
17         106  Washing Machine  28000  Home Appliances       30    2
18         107     Refrigerator  35000  Home Appliances        7    1
19         107     Refrigerator  35000  Home Appliances       19    2

     sale_date  total_sales
0   2025-01-05        55002
1   2025-02-10        55001
2   2025-03-15        55002
3   2025-01-08        25003
4   2025-02-12        25002
5   2025-03-18        25001
15  2025-01-18        28002
16  2025-02-22        28003
17  2025-03-28        28002
18  2025-01-20        35001
19  2025-03-01        35002

    product_id product_name  price category_name  sale_id  qty   sale_date  \
7          103   Headphones   3000   Electronics       15    7  2025-02-15
8          103   Headphones   3000   Electronics       27    6  2025-03-20
9          104      T-Shirt    800      Clothing        4   10  2025-01-12
10         104      T-Shirt    800      Clothing       16   12  2025-02-18
11         104      T-Shirt    800      Clothing       28    9  2025-03-22
12         105        Jeans   1800      Clothing        5    8  2025-01-15
20         108  Python Book    650         Books        8   12  2025-01-22
21         108  Python Book    650         Books       20   10  2025-03-03
22         109     SQL Book    500         Books        9   15  2025-01-25
23         109     SQL Book    500         Books       21    8  2025-03-05
24         110  Cricket Bat   2500        Sports       10    6  2025-02-02
26         111     Football   1200        Sports       11    8  2025-02-05
27         111     Football   1200        Sports       23    7  2025-03-10

    total_sales
7          3007
8          3006
9           810
10          812
11          809
12         1808
20          662
21          660
22          515
23          508
24         2506
26         1208
27         1207

In [ ]:
print(final_df[final_df['qty']>5])

    product_id product_name  price category_name  sale_id  qty   sale_date  \
7          103   Headphones   3000   Electronics       15    7  2025-02-15
8          103   Headphones   3000   Electronics       27    6  2025-03-20
9          104      T-Shirt    800      Clothing        4   10  2025-01-12
10         104      T-Shirt    800      Clothing       16   12  2025-02-18
11         104      T-Shirt    800      Clothing       28    9  2025-03-22
12         105        Jeans   1800      Clothing        5    8  2025-01-15
20         108  Python Book    650         Books        8   12  2025-01-22
21         108  Python Book    650         Books       20   10  2025-03-03
22         109     SQL Book    500         Books        9   15  2025-01-25
23         109     SQL Book    500         Books       21    8  2025-03-05
24         110  Cricket Bat   2500        Sports       10    6  2025-02-02
26         111     Football   1200        Sports       11    8  2025-02-05
27         111     Football   1200        Sports       23    7  2025-03-10

    total_sales
7          3007
8          3006
9           810
10          812
11          809
12         1808
20          662
21          660
22          515
23          508
24         2506
26         1208
27         1207

In [26]:

print(final_df[final_df['category_name']=='Electronics'])

    product_id product_name  price category_name  sale_id  qty   sale_date  \
0          101       Laptop  55000   Electronics        1    2  2025-01-05
1          101       Laptop  55000   Electronics       13    1  2025-02-10
2          101       Laptop  55000   Electronics       25    2  2025-03-15
3          102       Mobile  25000   Electronics        2    3  2025-01-08
4          102       Mobile  25000   Electronics       14    2  2025-02-12
5          102       Mobile  25000   Electronics       26    1  2025-03-18
6          103   Headphones   3000   Electronics        3    5  2025-01-10
7          103   Headphones   3000   Electronics       15    7  2025-02-15
8          103   Headphones   3000   Electronics       27    6  2025-03-20
28         112  Smart Watch   7000   Electronics       12    4  2025-02-08
29         112  Smart Watch   7000   Electronics       24    3  2025-03-12

    total_sales
0         55002
1         55001
2         55002
3         25003
4         25002
5         25001
6          3005
7          3007
8          3006
28         7004
29         7003

In [27]:

print(final_df[final_df['total_sales']>50000])

   product_id product_name  price category_name  sale_id  qty   sale_date  \
0         101       Laptop  55000   Electronics        1    2  2025-01-05
1         101       Laptop  55000   Electronics       13    1  2025-02-10
2         101       Laptop  55000   Electronics       25    2  2025-03-15

   total_sales
0        55002
1        55001
2        55002

In [31]:
# Task 7: GroupBy Analysis
#     Calculate total sales category-wise.

gp = final_df.groupby(by="category_name")

print(gp['total_sales'].sum())
print()

#     Calculate total quantity sold category-wise.
print(gp['qty'].sum())
print()

#     Calculate average price category-wise.
print(gp['price'].mean())
print()

#     Calculate total sales product-wise.
product_gp = final_df.groupby(by="product_name")
product_gp['total_sales'].sum()
print()

#     Find the category with the highest sales.
print(gp['total_sales'].sum())
print()

category_name
Books                2345
Clothing             7848
Electronics        263036
Home Appliances    154010
Sports               7425
Name: total_sales, dtype: int64

category_name
Books              45
Clothing           48
Electronics        36
Home Appliances    10
Sports             25
Name: qty, dtype: int64

category_name
Books                575.000000
Clothing            1300.000000
Electronics        23909.090909
Home Appliances    30800.000000
Sports              1850.000000
Name: price, dtype: float64


category_name
Books                2345
Clothing             7848
Electronics        263036
Home Appliances    154010
Sports               7425
Name: total_sales, dtype: int64

In [48]:

# Task 8: Business Questions
#     Which product generated the highest sales?
#     Which category generated the highest sales?
#     What is the total revenue generated by the company?
#     Which product sold the highest quantity?
#     What is the average sales value per transaction?

print(final_df.loc[final_df['total_sales'].idxmax()])
print()

print(max(gp['total_sales']))
print()

product_id               101
product_name          Laptop
price                  55000
category_name    Electronics
sale_id                    1
qty                        2
sale_date         2025-01-05
total_sales            55002
Name: 0, dtype: object

('Sports', 24    2506
25    2504
26    1208
27    1207
Name: total_sales, dtype: int64)

In [44]:
print(final_df['total_sales'].sum())
print()

434664

In [47]:
prod_qty = product_gp['qty'].sum()
print(prod_qty.idxmax())

T-Shirt

In [46]:
print(final_df['total_sales'].mean())

14488.8