In [1]:
# Pandas Election Data Analysis Task
# File 1: candidates.csv
# candidate_id	candidate_name	party
# C101	Rahul Sharma	BJP
# C102	Priya Patil	INC
# C103	Amit Verma	BJP
# C104	Neha Singh	AAP
# C105	Karan Gupta	INC

# File 2: constituencies.csv
# constituency_id	constituency_name	state
# S01	Nagpur Central	Maharashtra
# S02	Pune City	Maharashtra
# S03	Indore East	Madhya Pradesh
# S04	Delhi North	Delhi
# S05	Jaipur South	Rajasthan

# File 3: election_results.csv
# result_id	candidate_id	constituency_id	votes
# 1	C101	S01	85000
# 2	C102	S02	78000
# 3	C103	S03	NaN
# 4	C104	S04	65000
# 5	C105	S05	72000
# 5	C105	S05	72000

In [2]:
import pandas as pd

In [3]:
# Tasks
# Task 1: Load Data
#     Load all CSV files into Pandas DataFrames.

candidate_df = pd.read_csv('candidates.csv')
candidate_df

  candidate_id candidate_name party
0         C101   Rahul Sharma   BJP
1         C102    Priya Patil   INC
2         C103     Amit Verma   BJP
3         C104     Neha Singh   AAP
4         C105    Karan Gupta   INC

In [4]:
constituencies_df = pd.read_csv('constituencies.csv')
constituencies_df

  constituency_id constituency_name           state
0             S01    Nagpur Central     Maharashtra
1             S02         Pune City     Maharashtra
2             S03       Indore East  Madhya Pradesh
3             S04             Delhi     North Delhi
4             S05      Jaipur South       Rajasthan

In [5]:
election_result_df = pd.read_csv('election_results.csv')
election_result_df

   result_id candidate_id constituency_id    votes
0          1         C101             S01  85000.0
1          2         C102             S02  78000.0
2          3         C103             S03      NaN
3          4         C104             S04  65000.0
4          5         C105             S05  72000.0
5          5         C105             S05  72000.0

In [6]:

# Task 2: Basic Inspection
#     Display first 5 rows
#     Check shape
#     Check data types
#     Check column names
print(candidate_df.head())
print()
print(candidate_df.shape)
print()
print(candidate_df.dtypes)
print()
print(candidate_df.columns)

  candidate_id candidate_name party
0         C101   Rahul Sharma   BJP
1         C102    Priya Patil   INC
2         C103     Amit Verma   BJP
3         C104     Neha Singh   AAP
4         C105    Karan Gupta   INC

(5, 3)

candidate_id      object
candidate_name    object
party             object
dtype: object

Index(['candidate_id', 'candidate_name', 'party'], dtype='object')

In [7]:
# Task 3: Null Value Handling
#     Check Null Values
#     Replace Null Votes
#     Replace missing votes with average votes.
election_result_df.isnull().sum()
avg = election_result_df['votes'].mean()
election_result_df.fillna(avg,inplace=True)
election_result_df

   result_id candidate_id constituency_id    votes
0          1         C101             S01  85000.0
1          2         C102             S02  78000.0
2          3         C103             S03  74400.0
3          4         C104             S04  65000.0
4          5         C105             S05  72000.0
5          5         C105             S05  72000.0

In [8]:
# Task 4: Duplicate Handling
#     Check Duplicates
#     Remove Duplicates
print(election_result_df.duplicated().sum())
print(constituencies_df.duplicated().sum())
print(candidate_df.duplicated().sum())
election_result_df.drop_duplicates()

1
0
0

   result_id candidate_id constituency_id    votes
0          1         C101             S01  85000.0
1          2         C102             S02  78000.0
2          3         C103             S03  74400.0
3          4         C104             S04  65000.0
4          5         C105             S05  72000.0

In [9]:
# Task 5: Merge Data

#     Merge all three files into one DataFrame.

#     Final Columns
#     candidate_name	party	constituency_name	state	votes

df1 = pd.merge(election_result_df,candidate_df, how="inner", on='candidate_id')
df1

   result_id candidate_id constituency_id    votes candidate_name party
0          1         C101             S01  85000.0   Rahul Sharma   BJP
1          2         C102             S02  78000.0    Priya Patil   INC
2          3         C103             S03  74400.0     Amit Verma   BJP
3          4         C104             S04  65000.0     Neha Singh   AAP
4          5         C105             S05  72000.0    Karan Gupta   INC
5          5         C105             S05  72000.0    Karan Gupta   INC

In [10]:
df2 = pd.merge(df1, constituencies_df, how="inner", on = 'constituency_id')
df2

,result_id,candidate_id,constituency_id,votes,candidate_name,party,constituency_name,state
0,1,C101,S01,85000.0,Rahul Sharma,BJP,Nagpur Central,Maharashtra
1,2,C102,S02,78000.0,Priya Patil,INC,Pune City,Maharashtra
2,3,C103,S03,74400.0,Amit Verma,BJP,Indore East,Madhya Pradesh
3,4,C104,S04,65000.0,Neha Singh,AAP,Delhi,North Delhi
4,5,C105,S05,72000.0,Karan Gupta,INC,Jaipur South,Rajasthan
5,5,C105,S05,72000.0,Karan Gupta,INC,Jaipur South,Rajasthan

In [11]:
result = df2[['candidate_name','party','constituency_name','state','votes']]
result

  candidate_name party constituency_name           state    votes
0   Rahul Sharma   BJP    Nagpur Central     Maharashtra  85000.0
1    Priya Patil   INC         Pune City     Maharashtra  78000.0
2     Amit Verma   BJP       Indore East  Madhya Pradesh  74400.0
3     Neha Singh   AAP             Delhi     North Delhi  65000.0
4    Karan Gupta   INC      Jaipur South       Rajasthan  72000.0
5    Karan Gupta   INC      Jaipur South       Rajasthan  72000.0

In [12]:
# Task 6: Apply Function
#     Create a column:
#     vote_category
#     Condition:
#     Votes > 80000       High
#     Votes > 70000       Medium
#     Else                Low
def cal_vote_category(vote):
    if int(vote)>80000:
        return 'High'
    elif int(vote)>70000:
        return 'Medium'
    else:
        return 'Low'
result['vote_category'] = result['votes'].apply(cal_vote_category)
result

C:\Users\Admin\AppData\Local\Temp\ipykernel_1684\2204012953.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  result['vote_category'] = result['votes'].apply(cal_vote_category)

,candidate_name,party,constituency_name,state,votes,vote_category
0,Rahul Sharma,BJP,Nagpur Central,Maharashtra,85000.0,High
1,Priya Patil,INC,Pune City,Maharashtra,78000.0,Medium
2,Amit Verma,BJP,Indore East,Madhya Pradesh,74400.0,Medium
3,Neha Singh,AAP,Delhi,North Delhi,65000.0,Low
4,Karan Gupta,INC,Jaipur South,Rajasthan,72000.0,Medium
5,Karan Gupta,INC,Jaipur South,Rajasthan,72000.0,Medium

In [13]:
# Task 7: Filtering
# Find:
#     All BJP candidates
#     All INC candidates
#     Candidates from Maharashtra
#     Candidates with votes greater than 75000
#     Constituencies in Delhi
print(result[result['party'] == 'BJP'])
print()
print(result[result['party'] == 'INC'])

  candidate_name party constituency_name           state    votes  \
0   Rahul Sharma   BJP    Nagpur Central     Maharashtra  85000.0
2     Amit Verma   BJP       Indore East  Madhya Pradesh  74400.0

  vote_category
0          High
2        Medium

  candidate_name party constituency_name        state    votes vote_category
1    Priya Patil   INC         Pune City  Maharashtra  78000.0        Medium
4    Karan Gupta   INC      Jaipur South    Rajasthan  72000.0        Medium
5    Karan Gupta   INC      Jaipur South    Rajasthan  72000.0        Medium

In [14]:
result[result['state'] == 'Maharashtra']

  candidate_name party constituency_name        state    votes vote_category
0   Rahul Sharma   BJP    Nagpur Central  Maharashtra  85000.0          High
1    Priya Patil   INC         Pune City  Maharashtra  78000.0        Medium

In [15]:
result[result['votes']>75000]

  candidate_name party constituency_name        state    votes vote_category
0   Rahul Sharma   BJP    Nagpur Central  Maharashtra  85000.0          High
1    Priya Patil   INC         Pune City  Maharashtra  78000.0        Medium

In [16]:
result[result['constituency_name'] == 'Delhi']

  candidate_name party constituency_name        state    votes vote_category
3     Neha Singh   AAP             Delhi  North Delhi  65000.0           Low

In [17]:
# Task 8: Aggregate Functions
# Calculate:
#     Total Votes
#     Average Votes
#     Maximum Votes
#     Minimum Votes
#     Count of Candidates

print(result['votes'].sum())
print(result['votes'].mean())
print(result['votes'].max())
print(result['votes'].min())
print(result['votes'].count())

446400.0
74400.0
85000.0
65000.0
6

In [18]:
# Task 9: Grouping
#     Party-wise Total Votes
#     State-wise Total Votes
#     Party-wise Average Votes
#     State-wise Maximum Votes

party_gp = result.groupby(by='party')
print(party_gp['votes'].sum())
print()

state_gp = result.groupby(by='state')
print(state_gp['votes'].sum())
print()

print(party_gp['votes'].mean())
print()

print(state_gp['votes'].max())

party
AAP     65000.0
BJP    159400.0
INC    222000.0
Name: votes, dtype: float64

state
Madhya Pradesh     74400.0
Maharashtra       163000.0
North Delhi        65000.0
Rajasthan         144000.0
Name: votes, dtype: float64

party
AAP    65000.0
BJP    79700.0
INC    74000.0
Name: votes, dtype: float64

state
Madhya Pradesh    74400.0
Maharashtra       85000.0
North Delhi       65000.0
Rajasthan         72000.0
Name: votes, dtype: float64

In [19]:
# Task 10: Sorting
#     Sort by Votes Descending
#     Sort by Candidate Name Ascending
result.sort_values(by='votes', ascending=False)

,candidate_name,party,constituency_name,state,votes,vote_category
0,Rahul Sharma,BJP,Nagpur Central,Maharashtra,85000.0,High
1,Priya Patil,INC,Pune City,Maharashtra,78000.0,Medium
2,Amit Verma,BJP,Indore East,Madhya Pradesh,74400.0,Medium
4,Karan Gupta,INC,Jaipur South,Rajasthan,72000.0,Medium
5,Karan Gupta,INC,Jaipur South,Rajasthan,72000.0,Medium
3,Neha Singh,AAP,Delhi,North Delhi,65000.0,Low

In [20]:
result.sort_values(by='candidate_name')

,candidate_name,party,constituency_name,state,votes,vote_category
2,Amit Verma,BJP,Indore East,Madhya Pradesh,74400.0,Medium
4,Karan Gupta,INC,Jaipur South,Rajasthan,72000.0,Medium
5,Karan Gupta,INC,Jaipur South,Rajasthan,72000.0,Medium
3,Neha Singh,AAP,Delhi,North Delhi,65000.0,Low
1,Priya Patil,INC,Pune City,Maharashtra,78000.0,Medium
0,Rahul Sharma,BJP,Nagpur Central,Maharashtra,85000.0,High

In [21]:
# Task 11: Advanced Analysis
# Find Winning Candidate from Each State

id = result.groupby(by='state')['votes'].idxmax()
winner = result.loc[id]
winner

# Hint:
# groupby('state')['votes'].idxmax()

,candidate_name,party,constituency_name,state,votes,vote_category
2,Amit Verma,BJP,Indore East,Madhya Pradesh,74400.0,Medium
0,Rahul Sharma,BJP,Nagpur Central,Maharashtra,85000.0,High
3,Neha Singh,AAP,Delhi,North Delhi,65000.0,Low
4,Karan Gupta,INC,Jaipur South,Rajasthan,72000.0,Medium

In [22]:
# Find Party with Highest Total Votes
# Hint:
#     groupby('party')['votes'].sum()

party_votes = result.groupby(by='state')['votes'].sum()
print(party_votes.idxmax(), party_votes.max())

Maharashtra 163000.0

In [23]:
# Top 3 Candidates by Votes
# Hint:
#     nlargest()

print(result.nlargest(3,'votes'))

  candidate_name party constituency_name           state    votes  \
0   Rahul Sharma   BJP    Nagpur Central     Maharashtra  85000.0
1    Priya Patil   INC         Pune City     Maharashtra  78000.0
2     Amit Verma   BJP       Indore East  Madhya Pradesh  74400.0

  vote_category
0          High
1        Medium
2        Medium

In [24]:
# Bottom 3 Candidates by Votes
# Hint:
#     nsmallest()

print(result.nsmallest(3,'votes'))

  candidate_name party constituency_name        state    votes vote_category
3     Neha Singh   AAP             Delhi  North Delhi  65000.0           Low
4    Karan Gupta   INC      Jaipur South    Rajasthan  72000.0        Medium
5    Karan Gupta   INC      Jaipur South    Rajasthan  72000.0        Medium

In [25]:
# Task 12: Business Questions
#     Which party received the highest total votes?
print(result.groupby(by='party')['votes'].sum().max())
print()

#     Which state recorded the highest votes?
print(result.groupby(by='state')['votes'].sum().max())
print()

#     Who is the top-performing candidate?
print(result[result['votes']==result['votes'].max()])
print()

#     Which constituency had the highest votes?
print(result.loc[result.groupby(by='constituency_name')['votes'].idxmax()])
print()

#     What percentage of total votes did each party receive?
print(result.groupby(by='party'))
print()

#     Which party has the highest average votes per candidate?
avg_votes = result.groupby(by='party')['votes'].mean()
print(avg_votes.idxmax(), avg_votes.max())
print()

#     How many constituencies were won by each party?
print(result.loc[result.groupby('constituency_name')['votes'].idxmax()]['party'].value_counts())

222000.0

163000.0

  candidate_name party constituency_name        state    votes vote_category
0   Rahul Sharma   BJP    Nagpur Central  Maharashtra  85000.0          High

  candidate_name party constituency_name           state    votes  \
3     Neha Singh   AAP             Delhi     North Delhi  65000.0
2     Amit Verma   BJP       Indore East  Madhya Pradesh  74400.0
4    Karan Gupta   INC      Jaipur South       Rajasthan  72000.0
0   Rahul Sharma   BJP    Nagpur Central     Maharashtra  85000.0
1    Priya Patil   INC         Pune City     Maharashtra  78000.0

  vote_category
3           Low
2        Medium
4        Medium
0          High
1        Medium

<pandas.core.groupby.generic.DataFrameGroupBy object at 0x0000021C3960D260>

BJP 79700.0

party
BJP    2
INC    2
AAP    1
Name: count, dtype: int64