In [ ]:
# Pandas Election Data Analysis Task
# File 1: candidates.csv
# candidate_id	candidate_name	party
# C101	Rahul Sharma	BJP
# C102	Priya Patil	INC
# C103	Amit Verma	BJP
# C104	Neha Singh	AAP
# C105	Karan Gupta	INC

# File 2: constituencies.csv
# constituency_id	constituency_name	state
# S01	Nagpur Central	Maharashtra
# S02	Pune City	Maharashtra
# S03	Indore East	Madhya Pradesh
# S04	Delhi North	Delhi
# S05	Jaipur South	Rajasthan

# File 3: election_results.csv
# result_id	candidate_id	constituency_id	votes
# 1	C101	S01	85000
# 2	C102	S02	78000
# 3	C103	S03	NaN
# 4	C104	S04	65000
# 5	C105	S05	72000
# 5	C105	S05	72000

In [2]:
import pandas as pd

In [4]:
# Tasks
# Task 1: Load Data
#     Load all CSV files into Pandas DataFrames.

candidate_df = pd.read_csv('candidates.csv')
candidate_df

  candidate_id candidate_name party
0         C101   Rahul Sharma   BJP
1         C102    Priya Patil   INC
2         C103     Amit Verma   BJP
3         C104     Neha Singh   AAP
4         C105    Karan Gupta   INC

In [7]:
constituencies_df = pd.read_csv('constituencies.csv')
constituencies_df

  constituency_id constituency_name           state
0             S01    Nagpur Central     Maharashtra
1             S02         Pune City     Maharashtra
2             S03       Indore East  Madhya Pradesh
3             S04             Delhi     North Delhi
4             S05      Jaipur South       Rajasthan

In [9]:
election_result_df = pd.read_csv('election_results.csv')
election_result_df

   result_id candidate_id constituency_id    votes
0          1         C101             S01  85000.0
1          2         C102             S02  78000.0
2          3         C103             S03      NaN
3          4         C104             S04  65000.0
4          5         C105             S05  72000.0
5          5         C105             S05  72000.0

In [13]:

# Task 2: Basic Inspection
#     Display first 5 rows
#     Check shape
#     Check data types
#     Check column names
print(candidate_df.head())
print()
print(candidate_df.shape)
print()
print(candidate_df.dtypes)
print()
print(candidate_df.columns)

  candidate_id candidate_name party
0         C101   Rahul Sharma   BJP
1         C102    Priya Patil   INC
2         C103     Amit Verma   BJP
3         C104     Neha Singh   AAP
4         C105    Karan Gupta   INC

(5, 3)

candidate_id      object
candidate_name    object
party             object
dtype: object

Index(['candidate_id', 'candidate_name', 'party'], dtype='object')

In [24]:
# Task 3: Null Value Handling
#     Check Null Values
#     Replace Null Votes
#     Replace missing votes with average votes.
election_result_df.isnull().sum()
avg = election_result_df['votes'].mean()
election_result_df.fillna(avg,inplace=True)
election_result_df

   result_id candidate_id constituency_id    votes
0          1         C101             S01  85000.0
1          2         C102             S02  78000.0
2          3         C103             S03  74400.0
3          4         C104             S04  65000.0
4          5         C105             S05  72000.0
5          5         C105             S05  72000.0

In [25]:
# Task 4: Duplicate Handling
#     Check Duplicates
#     Remove Duplicates
print(election_result_df.duplicated().sum())
print(constituencies_df.duplicated().sum())
print(candidate_df.duplicated().sum())
election_result_df.drop_duplicates()

1
0
0

   result_id candidate_id constituency_id    votes
0          1         C101             S01  85000.0
1          2         C102             S02  78000.0
2          3         C103             S03  74400.0
3          4         C104             S04  65000.0
4          5         C105             S05  72000.0

In [30]:
# Task 5: Merge Data

#     Merge all three files into one DataFrame.

#     Final Columns
#     candidate_name	party	constituency_name	state	votes

df1 = pd.merge(election_result_df,candidate_df, how="inner", on='candidate_id')
df1

   result_id candidate_id constituency_id    votes candidate_name party
0          1         C101             S01  85000.0   Rahul Sharma   BJP
1          2         C102             S02  78000.0    Priya Patil   INC
2          3         C103             S03  74400.0     Amit Verma   BJP
3          4         C104             S04  65000.0     Neha Singh   AAP
4          5         C105             S05  72000.0    Karan Gupta   INC
5          5         C105             S05  72000.0    Karan Gupta   INC

In [31]:
df2 = pd.merge(df1, constituencies_df, how="inner", on = 'constituency_id')
df2

,result_id,candidate_id,constituency_id,votes,candidate_name,party,constituency_name,state
0,1,C101,S01,85000.0,Rahul Sharma,BJP,Nagpur Central,Maharashtra
1,2,C102,S02,78000.0,Priya Patil,INC,Pune City,Maharashtra
2,3,C103,S03,74400.0,Amit Verma,BJP,Indore East,Madhya Pradesh
3,4,C104,S04,65000.0,Neha Singh,AAP,Delhi,North Delhi
4,5,C105,S05,72000.0,Karan Gupta,INC,Jaipur South,Rajasthan
5,5,C105,S05,72000.0,Karan Gupta,INC,Jaipur South,Rajasthan

In [32]:
result = df2[['candidate_name','party','constituency_name','state','votes']]
result

  candidate_name party constituency_name           state    votes
0   Rahul Sharma   BJP    Nagpur Central     Maharashtra  85000.0
1    Priya Patil   INC         Pune City     Maharashtra  78000.0
2     Amit Verma   BJP       Indore East  Madhya Pradesh  74400.0
3     Neha Singh   AAP             Delhi     North Delhi  65000.0
4    Karan Gupta   INC      Jaipur South       Rajasthan  72000.0
5    Karan Gupta   INC      Jaipur South       Rajasthan  72000.0

In [ ]:
# Task 6: Apply Function
#     Create a column:
#     vote_category
#     Condition:
#     Votes > 80000       High
#     Votes > 70000       Medium
#     Else                Low

In [ ]:
# Task 7: Filtering
# Find:
#     All BJP candidates
#     All INC candidates
#     Candidates from Maharashtra
#     Candidates with votes greater than 75000
#     Constituencies in Delhi

In [ ]:
# Task 8: Aggregate Functions
# Calculate:
#     Total Votes
#     Average Votes
#     Maximum Votes
#     Minimum Votes
#     Count of Candidates

In [ ]:
# Task 9: Grouping
#     Party-wise Total Votes
#     State-wise Total Votes
#     Party-wise Average Votes
#     State-wise Maximum Votes

In [ ]:
# Task 10: Sorting
#     Sort by Votes Descending
#     Sort by Candidate Name Ascending

In [ ]:
# Task 11: Advanced Analysis
# Find Winning Candidate from Each State

# Hint:
# groupby('state')['votes'].idxmax()
# Find Party with Highest Total Votes
# Hint:
#     groupby('party')['votes'].sum()
# Top 3 Candidates by Votes
# Hint:
#     nlargest()
# Bottom 3 Candidates by Votes
# Hint:
#     nsmallest()

In [ ]:
# Task 12: Business Questions
#     Which party received the highest total votes?
#     Which state recorded the highest votes?
#     Who is the top-performing candidate?
#     Which constituency had the highest votes?
#     What percentage of total votes did each party receive?
#     Which party has the highest average votes per candidate?
#     How many constituencies were won by each party?