In [ ]:
# Task 1: Load CSV File

#     Create a CSV file named students.csv.

#     roll,name,course,fees,city
#     1,Amit,Python,25000,Pune
#     2,Neha,Data Science,45000,Mumbai
#     3,Rahul,Python,25000,Nagpur
#     4,Priya,Java,30000,Pune
#     5,Rohan,Data Analytics,40000,Nashik
#     6,Sneha,Java,30000,Mumbai
#     7,Karan,Python,25000,Pune
#     8,Pooja,Data Science,45000,Nagpur
#     9,Ajay,Data Analytics,40000,Pune
#     10,Meena,Java,30000,Nashik
# Load this file into a DataFrame.

In [50]:
import pandas as pd
student_data = pd.read_csv("student_data.csv")
student_data

   roll   name          course   fees    city
0     1   Amit          Python  25000    Pune
1     2   Neha    Data Science  45000  Mumbai
2     3  Rahul          Python  25000  Nagpur
3     4  Priya            Java  30000    Pune
4     5  Rohan  Data Analytics  40000  Nashik
5     6  Sneha            Java  30000  Mumbai
6     7  Karan          Python  25000    Pune
7     8  Pooja    Data Science  45000  Nagpur
8     9   Ajay  Data Analytics  40000    Pune
9    10  Meena            Java  30000  Nashik

In [6]:
# Task 2: Access Columns
#     Display only name column.
#     Display name and course columns.
#     Display fees column.
#     Find datatype of each column.

student_data['name']

student_data[['name','course']]

student_data['fees']

student_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   roll    10 non-null     int64
 1   name    10 non-null     object
 2   course  10 non-null     object
 3   fees    10 non-null     int64
 4   city    10 non-null     object
dtypes: int64(2), object(3)
memory usage: 532.0+ bytes

In [45]:
# Task 4: Add New Column
#     Add a column named GST.
#     GST = fees * 0.18
#     Expected:
#     fees	GST
#     25000	4500
#     45000	8100

student_data['GST'] = student_data['fees']*0.18

student_data

   roll   name          course   fees    city     GST
0     1   Amit          Python  25000    Pune  4500.0
1     2   Neha    Data Science  45000  Mumbai  8100.0
2     3  Rahul          Python  25000  Nagpur  4500.0
3     4  Priya            Java  30000    Pune  5400.0
4     5  Rohan  Data Analytics  40000  Nashik  7200.0
5     6  Sneha            Java  30000  Mumbai  5400.0
6     7  Karan          Python  25000    Pune  4500.0
7     8  Pooja    Data Science  45000  Nagpur  8100.0
8     9   Ajay  Data Analytics  40000    Pune  7200.0
9    10  Meena            Java  30000  Nashik  5400.0

In [46]:
# Task 5: Calculate New Column
#     Create:
#     total_fees = fees + GST
#     Output:
#     fees	GST	total_fees
#     25000	4500	29500

student_data['total_fees'] = student_data['fees'] + student_data['GST']
student_data

   roll   name          course   fees    city     GST  total_fees
0     1   Amit          Python  25000    Pune  4500.0     29500.0
1     2   Neha    Data Science  45000  Mumbai  8100.0     53100.0
2     3  Rahul          Python  25000  Nagpur  4500.0     29500.0
3     4  Priya            Java  30000    Pune  5400.0     35400.0
4     5  Rohan  Data Analytics  40000  Nashik  7200.0     47200.0
5     6  Sneha            Java  30000  Mumbai  5400.0     35400.0
6     7  Karan          Python  25000    Pune  4500.0     29500.0
7     8  Pooja    Data Science  45000  Nagpur  8100.0     53100.0
8     9   Ajay  Data Analytics  40000    Pune  7200.0     47200.0
9    10  Meena            Java  30000  Nashik  5400.0     35400.0

In [51]:
# Task 6: Add New Row
# Add:
#     11,Vaibhav,AWS,35000,Pune
#     to the DataFrame.

student_data.loc[10] = ['11','Vaibhav','AWS','35000','Pune']
student_data

   roll     name          course   fees    city
0     1     Amit          Python  25000    Pune
1     2     Neha    Data Science  45000  Mumbai
2     3    Rahul          Python  25000  Nagpur
3     4    Priya            Java  30000    Pune
4     5    Rohan  Data Analytics  40000  Nashik
5     6    Sneha            Java  30000  Mumbai
6     7    Karan          Python  25000    Pune
7     8    Pooja    Data Science  45000  Nagpur
8     9     Ajay  Data Analytics  40000    Pune
9    10    Meena            Java  30000  Nashik
10   11  Vaibhav             AWS  35000    Pune

In [37]:
# Task 7: Rename Columns
#     Rename:
#     name â†’ student_name
#     fees â†’ course_fee
#     city â†’ location

student_data.rename(columns={
    "name" : "student_name",
    'fees' : "course_fee",
    'city' : "location"
}, inplace=True)

student_data

   roll student_name          course  course_fee location     GST  total_fees
0     1         Amit          Python       25000     Pune  4500.0     29500.0
1     2         Neha    Data Science       45000   Mumbai  8100.0     53100.0
2     3        Rahul          Python       25000   Nagpur  4500.0     29500.0
3     4        Priya            Java       30000     Pune  5400.0     35400.0
4     5        Rohan  Data Analytics       40000   Nashik  7200.0     47200.0
5     6        Sneha            Java       30000   Mumbai  5400.0     35400.0
6     7        Karan          Python       25000     Pune  4500.0     29500.0
7     8        Pooja    Data Science       45000   Nagpur  8100.0     53100.0
8     9         Ajay  Data Analytics       40000     Pune  7200.0     47200.0
9    10        Meena            Java       30000   Nashik  5400.0     35400.0

In [39]:
# Task 8: Filtering
#     Single Condition
#     Students from Pune.

student_data[student_data['location'] == 'Pune']

#     Students whose fees > 30000.

student_data[student_data['course_fee']>30000]

#     Multiple Conditions
#     Students from Pune AND fees > 25000.
student_data[(student_data['location'] == 'Pune') & (student_data['course_fee'] > 25000)]

#     Students from Mumbai OR course = Java.
student_data[(student_data['location'] == 'Mumbai') | (student_data['course'] == 'Java')]

#     Students from Nagpur AND course = Data Science.
student_data[(student_data['location'] == 'Nagpur') & (student_data['course'] == 'Data Science')]

   roll student_name        course  course_fee location     GST  total_fees
7     8        Pooja  Data Science       45000   Nagpur  8100.0     53100.0

In [40]:
# Task 9: Sorting
#     Sort by fees ascending.
#     Sort by fees descending.
#     Sort by city and fees.

student_data.sort_values(by="course_fee")
student_data.sort_values(by="course_fee", ascending=False)
student_data.sort_values(by=['location','course_fee'])

   roll student_name          course  course_fee location     GST  total_fees
5     6        Sneha            Java       30000   Mumbai  5400.0     35400.0
1     2         Neha    Data Science       45000   Mumbai  8100.0     53100.0
2     3        Rahul          Python       25000   Nagpur  4500.0     29500.0
7     8        Pooja    Data Science       45000   Nagpur  8100.0     53100.0
9    10        Meena            Java       30000   Nashik  5400.0     35400.0
4     5        Rohan  Data Analytics       40000   Nashik  7200.0     47200.0
0     1         Amit          Python       25000     Pune  4500.0     29500.0
6     7        Karan          Python       25000     Pune  4500.0     29500.0
3     4        Priya            Java       30000     Pune  5400.0     35400.0
8     9         Ajay  Data Analytics       40000     Pune  7200.0     47200.0

In [17]:
# Task 10: Create Another CSV

#     payments.csv

payment = pd.read_csv('payments.csv')
payment

   roll  paid_fees
0     1      20000
1     2      40000
2     3      25000
3     4      25000
4     5      35000
5     6      30000
6     7      15000
7     8      45000
8     9      30000
9    10      28000

In [20]:
# Task 11: Merge DataFrames

# Load both files and perform:

#     ALL join operations

pd.merge(student_data,payment,how="inner", on="roll")

pd.merge(student_data,payment,how="left", on="roll")

pd.merge(student_data,payment,how="right", on="roll")

student = pd.merge(student_data,payment,how="outer", on="roll")
student

   roll   name          course   fees    city     GST  total_fees  paid_fees
0     1   Amit          Python  25000    Pune  4500.0     29500.0      20000
1     2   Neha    Data Science  45000  Mumbai  8100.0     53100.0      40000
2     3  Rahul          Python  25000  Nagpur  4500.0     29500.0      25000
3     4  Priya            Java  30000    Pune  5400.0     35400.0      25000
4     5  Rohan  Data Analytics  40000  Nashik  7200.0     47200.0      35000
5     6  Sneha            Java  30000  Mumbai  5400.0     35400.0      30000
6     7  Karan          Python  25000    Pune  4500.0     29500.0      15000
7     8  Pooja    Data Science  45000  Nagpur  8100.0     53100.0      45000
8     9   Ajay  Data Analytics  40000    Pune  7200.0     47200.0      30000
9    10  Meena            Java  30000  Nashik  5400.0     35400.0      28000

In [22]:
# Task 12: Remaining Fees Calculation
# After merge create:
# remaining_fees = fees - paid_fees

# Display:
# name	fees	paid_fees	remaining_fees

student['remaining_fees'] = student['fees'] - student['paid_fees']
student[['name','fees','paid_fees','remaining_fees']]

    name   fees  paid_fees  remaining_fees
0   Amit  25000      20000            5000
1   Neha  45000      40000            5000
2  Rahul  25000      25000               0
3  Priya  30000      25000            5000
4  Rohan  40000      35000            5000
5  Sneha  30000      30000               0
6  Karan  25000      15000           10000
7  Pooja  45000      45000               0
8   Ajay  40000      30000           10000
9  Meena  30000      28000            2000

In [30]:
# Task 13: Complex Filtering
#     Students whose remaining fees > 5000.
#     Students from Pune and remaining fees > 5000.
#     Students enrolled in Python and paid less than 20000.
#     Students from Mumbai or Nagpur with fees > 30000.

student[student['remaining_fees']>5000]

student[(student['city'] == 'Pune') & (student['remaining_fees']>5000)]

student[(student['course'] == 'Python') & (student['paid_fees']<20000)]

student[(student['city'].isin(['Mumbai','Nagpur'])) & (student['paid_fees']<30000)]

,roll,name,course,fees,city,GST,total_fees,paid_fees,remaining_fees
2,3,Rahul,Python,25000,Nagpur,4500.0,29500.0,25000,0