In [8]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_excel('Employee_Data_20_Records.xlsx')
df

    emp_id    name  gender  age  experience  salary department     rating
0     1001   Aarav    Male   23           2   32500         IT    Average
1     1002  Ananya  Female   24           3   35000    Finance  Excellent
2     1003   Rahul    Male   25           4   37500      Sales       Good
3     1004   Sneha  Female   26           5   40000  Marketing    Average
4     1005  Vikram    Male   27           6   42500         HR  Excellent
5     1006   Pooja  Female   28           7   45000         IT       Good
6     1007   Rohan    Male   29           8   47500    Finance    Average
7     1008    Neha  Female   30           9   50000      Sales  Excellent
8     1009   Karan    Male   31          10   52500  Marketing       Good
9     1010   Priya  Female   32           1   55000         HR    Average
10    1011   Arjun    Male   33           2   57500         IT  Excellent
11    1012   Kavya  Female   34           3   60000    Finance       Good
12    1013    Amit    Male   35           4   62500      Sales    Average
13    1014    Riya  Female   36           5   65000  Marketing  Excellent
14    1015   Sahil    Male   22           6   67500         HR       Good
15    1016   Meera  Female   23           7   70000         IT    Average
16    1017  Nikhil    Male   24           8   72500    Finance  Excellent
17    1018    Isha  Female   25           9   75000      Sales       Good
18    1019   Varun    Male   26          10   77500  Marketing    Average
19    1020    Diya  Female   27           1   80000         HR  Excellent

In [6]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
df['age'] = scaler.fit_transform(df[['age']])
df

    emp_id    name  gender       age  experience  salary department     rating
0     1001   Aarav    Male  0.071429           2   32500         IT    Average
1     1002  Ananya  Female  0.142857           3   35000    Finance  Excellent
2     1003   Rahul    Male  0.214286           4   37500      Sales       Good
3     1004   Sneha  Female  0.285714           5   40000  Marketing    Average
4     1005  Vikram    Male  0.357143           6   42500         HR  Excellent
5     1006   Pooja  Female  0.428571           7   45000         IT       Good
6     1007   Rohan    Male  0.500000           8   47500    Finance    Average
7     1008    Neha  Female  0.571429           9   50000      Sales  Excellent
8     1009   Karan    Male  0.642857          10   52500  Marketing       Good
9     1010   Priya  Female  0.714286           1   55000         HR    Average
10    1011   Arjun    Male  0.785714           2   57500         IT  Excellent
11    1012   Kavya  Female  0.857143           3   60000    Finance       Good
12    1013    Amit    Male  0.928571           4   62500      Sales    Average
13    1014    Riya  Female  1.000000           5   65000  Marketing  Excellent
14    1015   Sahil    Male  0.000000           6   67500         HR       Good
15    1016   Meera  Female  0.071429           7   70000         IT    Average
16    1017  Nikhil    Male  0.142857           8   72500    Finance  Excellent
17    1018    Isha  Female  0.214286           9   75000      Sales       Good
18    1019   Varun    Male  0.285714          10   77500  Marketing    Average
19    1020    Diya  Female  0.357143           1   80000         HR  Excellent

In [7]:
df['experience'] = scaler.fit_transform(df[['experience']])
df

    emp_id    name  gender       age  experience  salary department     rating
0     1001   Aarav    Male  0.071429    0.111111   32500         IT    Average
1     1002  Ananya  Female  0.142857    0.222222   35000    Finance  Excellent
2     1003   Rahul    Male  0.214286    0.333333   37500      Sales       Good
3     1004   Sneha  Female  0.285714    0.444444   40000  Marketing    Average
4     1005  Vikram    Male  0.357143    0.555556   42500         HR  Excellent
5     1006   Pooja  Female  0.428571    0.666667   45000         IT       Good
6     1007   Rohan    Male  0.500000    0.777778   47500    Finance    Average
7     1008    Neha  Female  0.571429    0.888889   50000      Sales  Excellent
8     1009   Karan    Male  0.642857    1.000000   52500  Marketing       Good
9     1010   Priya  Female  0.714286    0.000000   55000         HR    Average
10    1011   Arjun    Male  0.785714    0.111111   57500         IT  Excellent
11    1012   Kavya  Female  0.857143    0.222222   60000    Finance       Good
12    1013    Amit    Male  0.928571    0.333333   62500      Sales    Average
13    1014    Riya  Female  1.000000    0.444444   65000  Marketing  Excellent
14    1015   Sahil    Male  0.000000    0.555556   67500         HR       Good
15    1016   Meera  Female  0.071429    0.666667   70000         IT    Average
16    1017  Nikhil    Male  0.142857    0.777778   72500    Finance  Excellent
17    1018    Isha  Female  0.214286    0.888889   75000      Sales       Good
18    1019   Varun    Male  0.285714    1.000000   77500  Marketing    Average
19    1020    Diya  Female  0.357143    0.000000   80000         HR  Excellent

In [9]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
df['salary'] = scaler.fit_transform(df[['salary']])
df

,emp_id,name,gender,age,experience,salary,department,rating
0,1001,Aarav,Male,0.071429,0.111111,-1.647509,IT,Average
1,1002,Ananya,Female,0.142857,0.222222,-1.474087,Finance,Excellent
2,1003,Rahul,Male,0.214286,0.333333,-1.300665,Sales,Good
3,1004,Sneha,Female,0.285714,0.444444,-1.127243,Marketing,Average
4,1005,Vikram,Male,0.357143,0.555556,-0.953821,HR,Excellent
5,1006,Pooja,Female,0.428571,0.666667,-0.780399,IT,Good
6,1007,Rohan,Male,0.500000,0.777778,-0.606977,Finance,Average
7,1008,Neha,Female,0.571429,0.888889,-0.433555,Sales,Excellent
8,1009,Karan,Male,0.642857,1.000000,-0.260133,Marketing,Good
9,1010,Priya,Female,0.714286,0.000000,-0.086711,HR,Average
10,1011,Arjun,Male,0.785714,0.111111,0.086711,IT,Excellent
11,1012,Kavya,Female,0.857143,0.222222,0.260133,Finance,Good
12,1013,Amit,Male,0.928571,0.333333,0.433555,Sales,Average
13,1014,Riya,Female,1.000000,0.444444,0.606977,Marketing,Excellent
14,1015,Sahil,Male,0.000000,0.555556,0.780399,HR,Good
15,1016,Meera,Female,0.071429,0.666667,0.953821,IT,Average
16,1017,Nikhil,Male,0.142857,0.777778,1.127243,Finance,Excellent
17,1018,Isha,Female,0.214286,0.888889,1.300665,Sales,Good
18,1019,Varun,Male,0.285714,1.000000,1.474087,Marketing,Average
19,1020,Diya,Female,0.357143,0.000000,1.647509,HR,Excellent

In [10]:
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()
df['gender'] = encoder.fit_transform(df[['gender']])
df

c:\Users\Admin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\preprocessing\_label.py:110: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

,emp_id,name,gender,age,experience,salary,department,rating
0,1001,Aarav,1,0.071429,0.111111,-1.647509,IT,Average
1,1002,Ananya,0,0.142857,0.222222,-1.474087,Finance,Excellent
2,1003,Rahul,1,0.214286,0.333333,-1.300665,Sales,Good
3,1004,Sneha,0,0.285714,0.444444,-1.127243,Marketing,Average
4,1005,Vikram,1,0.357143,0.555556,-0.953821,HR,Excellent
5,1006,Pooja,0,0.428571,0.666667,-0.780399,IT,Good
6,1007,Rohan,1,0.500000,0.777778,-0.606977,Finance,Average
7,1008,Neha,0,0.571429,0.888889,-0.433555,Sales,Excellent
8,1009,Karan,1,0.642857,1.000000,-0.260133,Marketing,Good
9,1010,Priya,0,0.714286,0.000000,-0.086711,HR,Average
10,1011,Arjun,1,0.785714,0.111111,0.086711,IT,Excellent
11,1012,Kavya,0,0.857143,0.222222,0.260133,Finance,Good
12,1013,Amit,1,0.928571,0.333333,0.433555,Sales,Average
13,1014,Riya,0,1.000000,0.444444,0.606977,Marketing,Excellent
14,1015,Sahil,1,0.000000,0.555556,0.780399,HR,Good
15,1016,Meera,0,0.071429,0.666667,0.953821,IT,Average
16,1017,Nikhil,1,0.142857,0.777778,1.127243,Finance,Excellent
17,1018,Isha,0,0.214286,0.888889,1.300665,Sales,Good
18,1019,Varun,1,0.285714,1.000000,1.474087,Marketing,Average
19,1020,Diya,0,0.357143,0.000000,1.647509,HR,Excellent

In [11]:
from sklearn.preprocessing import OrdinalEncoder
encoder = OrdinalEncoder(categories=[['Average','Good','Excellent']])
df['rating'] = encoder.fit_transform(df[['rating']])
df

    emp_id    name  gender       age  experience    salary department  rating
0     1001   Aarav       1  0.071429    0.111111 -1.647509         IT     0.0
1     1002  Ananya       0  0.142857    0.222222 -1.474087    Finance     2.0
2     1003   Rahul       1  0.214286    0.333333 -1.300665      Sales     1.0
3     1004   Sneha       0  0.285714    0.444444 -1.127243  Marketing     0.0
4     1005  Vikram       1  0.357143    0.555556 -0.953821         HR     2.0
5     1006   Pooja       0  0.428571    0.666667 -0.780399         IT     1.0
6     1007   Rohan       1  0.500000    0.777778 -0.606977    Finance     0.0
7     1008    Neha       0  0.571429    0.888889 -0.433555      Sales     2.0
8     1009   Karan       1  0.642857    1.000000 -0.260133  Marketing     1.0
9     1010   Priya       0  0.714286    0.000000 -0.086711         HR     0.0
10    1011   Arjun       1  0.785714    0.111111  0.086711         IT     2.0
11    1012   Kavya       0  0.857143    0.222222  0.260133    Finance     1.0
12    1013    Amit       1  0.928571    0.333333  0.433555      Sales     0.0
13    1014    Riya       0  1.000000    0.444444  0.606977  Marketing     2.0
14    1015   Sahil       1  0.000000    0.555556  0.780399         HR     1.0
15    1016   Meera       0  0.071429    0.666667  0.953821         IT     0.0
16    1017  Nikhil       1  0.142857    0.777778  1.127243    Finance     2.0
17    1018    Isha       0  0.214286    0.888889  1.300665      Sales     1.0
18    1019   Varun       1  0.285714    1.000000  1.474087  Marketing     0.0
19    1020    Diya       0  0.357143    0.000000  1.647509         HR     2.0

In [12]:
data = pd.get_dummies(df, columns=['department'])
data

,emp_id,name,gender,age,experience,salary,rating,department_Finance,department_HR,department_IT,department_Marketing,department_Sales
0,1001,Aarav,1,0.071429,0.111111,-1.647509,0.0,False,False,True,False,False
1,1002,Ananya,0,0.142857,0.222222,-1.474087,2.0,True,False,False,False,False
2,1003,Rahul,1,0.214286,0.333333,-1.300665,1.0,False,False,False,False,True
3,1004,Sneha,0,0.285714,0.444444,-1.127243,0.0,False,False,False,True,False
4,1005,Vikram,1,0.357143,0.555556,-0.953821,2.0,False,True,False,False,False
5,1006,Pooja,0,0.428571,0.666667,-0.780399,1.0,False,False,True,False,False
6,1007,Rohan,1,0.500000,0.777778,-0.606977,0.0,True,False,False,False,False
7,1008,Neha,0,0.571429,0.888889,-0.433555,2.0,False,False,False,False,True
8,1009,Karan,1,0.642857,1.000000,-0.260133,1.0,False,False,False,True,False
9,1010,Priya,0,0.714286,0.000000,-0.086711,0.0,False,True,False,False,False
10,1011,Arjun,1,0.785714,0.111111,0.086711,2.0,False,False,True,False,False
11,1012,Kavya,0,0.857143,0.222222,0.260133,1.0,True,False,False,False,False
12,1013,Amit,1,0.928571,0.333333,0.433555,0.0,False,False,False,False,True
13,1014,Riya,0,1.000000,0.444444,0.606977,2.0,False,False,False,True,False
14,1015,Sahil,1,0.000000,0.555556,0.780399,1.0,False,True,False,False,False
15,1016,Meera,0,0.071429,0.666667,0.953821,0.0,False,False,True,False,False
16,1017,Nikhil,1,0.142857,0.777778,1.127243,2.0,True,False,False,False,False
17,1018,Isha,0,0.214286,0.888889,1.300665,1.0,False,False,False,False,True
18,1019,Varun,1,0.285714,1.000000,1.474087,0.0,False,False,False,True,False
19,1020,Diya,0,0.357143,0.000000,1.647509,2.0,False,True,False,False,False