In [1]:
import pandas as pd

In [2]:
student_df = pd.read_csv('student_data.csv')
student_df

,student_id,student_name,branch,course,final_test_marks,course_fee,paid_fee
0,S001,Aarav Patil,Karve Nagar,Data Science,34,50000,25000
1,S002,Vivaan Sharma,Nagpur,Data Analytics,23,40000,24000
2,S003,Aditya Verma,Deccan,Web Development,55,30000,21000
3,S004,Arjun Jadhav,Chinchwad,Testing,51,20000,16000
4,S005,Sai Pawar,Karve Nagar,Data Science,48,50000,45000
...,...,...,...,...,...,...,...
95,S096,Shubham Nair,Chinchwad,Testing,70,20000,8000
96,S097,Yash Singh,Karve Nagar,Data Science,78,50000,25000
97,S098,Aniket Mehta,Nagpur,Data Analytics,38,40000,24000
98,S099,Nikhil Agrawal,Deccan,Web Development,53,30000,21000
99,S100,Ruturaj Thakur,Chinchwad,Testing,37,20000,16000

In [3]:
student_df['student_id']

0     S001
1     S002
2     S003
3     S004
4     S005
      ...
95    S096
96    S097
97    S098
98    S099
99    S100
Name: student_id, Length: 100, dtype: object

In [4]:
student_df[['student_id','student_name','final_test_marks']]

   student_id    student_name  final_test_marks
0        S001     Aarav Patil                34
1        S002   Vivaan Sharma                23
2        S003    Aditya Verma                55
3        S004    Arjun Jadhav                51
4        S005       Sai Pawar                48
..        ...             ...               ...
95       S096    Shubham Nair                70
96       S097      Yash Singh                78
97       S098    Aniket Mehta                38
98       S099  Nikhil Agrawal                53
99       S100  Ruturaj Thakur                37

[100 rows x 3 columns]

In [5]:
student_df.iloc[0]

student_id                  S001
student_name         Aarav Patil
branch               Karve Nagar
course              Data Science
final_test_marks              34
course_fee                 50000
paid_fee                   25000
Name: 0, dtype: object

In [6]:
student_df.iloc[0:10]

,student_id,student_name,branch,course,final_test_marks,course_fee,paid_fee
0,S001,Aarav Patil,Karve Nagar,Data Science,34,50000,25000
1,S002,Vivaan Sharma,Nagpur,Data Analytics,23,40000,24000
2,S003,Aditya Verma,Deccan,Web Development,55,30000,21000
3,S004,Arjun Jadhav,Chinchwad,Testing,51,20000,16000
4,S005,Sai Pawar,Karve Nagar,Data Science,48,50000,45000
5,S006,Atharva Kulkarni,Nagpur,Data Analytics,37,40000,16000
6,S007,Om Deshmukh,Deccan,Web Development,33,30000,15000
7,S008,Rohan Shinde,Chinchwad,Testing,89,20000,12000
8,S009,Rahul More,Karve Nagar,Data Science,31,50000,35000
9,S010,Kunal Joshi,Nagpur,Data Analytics,95,40000,32000

In [7]:
student_df['r_fees'] = student_df['course_fee'] - student_df['paid_fee']
student_df

,student_id,student_name,branch,course,final_test_marks,course_fee,paid_fee,r_fees
0,S001,Aarav Patil,Karve Nagar,Data Science,34,50000,25000,25000
1,S002,Vivaan Sharma,Nagpur,Data Analytics,23,40000,24000,16000
2,S003,Aditya Verma,Deccan,Web Development,55,30000,21000,9000
3,S004,Arjun Jadhav,Chinchwad,Testing,51,20000,16000,4000
4,S005,Sai Pawar,Karve Nagar,Data Science,48,50000,45000,5000
...,...,...,...,...,...,...,...,...
95,S096,Shubham Nair,Chinchwad,Testing,70,20000,8000,12000
96,S097,Yash Singh,Karve Nagar,Data Science,78,50000,25000,25000
97,S098,Aniket Mehta,Nagpur,Data Analytics,38,40000,24000,16000
98,S099,Nikhil Agrawal,Deccan,Web Development,53,30000,21000,9000
99,S100,Ruturaj Thakur,Chinchwad,Testing,37,20000,16000,4000

In [8]:
student_df.drop(2,inplace=True)
student_df

,student_id,student_name,branch,course,final_test_marks,course_fee,paid_fee,r_fees
0,S001,Aarav Patil,Karve Nagar,Data Science,34,50000,25000,25000
1,S002,Vivaan Sharma,Nagpur,Data Analytics,23,40000,24000,16000
3,S004,Arjun Jadhav,Chinchwad,Testing,51,20000,16000,4000
4,S005,Sai Pawar,Karve Nagar,Data Science,48,50000,45000,5000
5,S006,Atharva Kulkarni,Nagpur,Data Analytics,37,40000,16000,24000
...,...,...,...,...,...,...,...,...
95,S096,Shubham Nair,Chinchwad,Testing,70,20000,8000,12000
96,S097,Yash Singh,Karve Nagar,Data Science,78,50000,25000,25000
97,S098,Aniket Mehta,Nagpur,Data Analytics,38,40000,24000,16000
98,S099,Nikhil Agrawal,Deccan,Web Development,53,30000,21000,9000
99,S100,Ruturaj Thakur,Chinchwad,Testing,37,20000,16000,4000

In [9]:
student_df.drop('branch',axis=1,inplace=True)
student_df

,student_id,student_name,course,final_test_marks,course_fee,paid_fee,r_fees
0,S001,Aarav Patil,Data Science,34,50000,25000,25000
1,S002,Vivaan Sharma,Data Analytics,23,40000,24000,16000
3,S004,Arjun Jadhav,Testing,51,20000,16000,4000
4,S005,Sai Pawar,Data Science,48,50000,45000,5000
5,S006,Atharva Kulkarni,Data Analytics,37,40000,16000,24000
...,...,...,...,...,...,...,...
95,S096,Shubham Nair,Testing,70,20000,8000,12000
96,S097,Yash Singh,Data Science,78,50000,25000,25000
97,S098,Aniket Mehta,Data Analytics,38,40000,24000,16000
98,S099,Nikhil Agrawal,Web Development,53,30000,21000,9000
99,S100,Ruturaj Thakur,Testing,37,20000,16000,4000

In [10]:
student_df.loc[100] = ['s101','Sakshi Jagatp','nagpur','DA','56','7000','4000']

In [11]:
student_df.loc[len(student_df)+1] = ['s101','Sakshi Jagatp','nagpur','DA','56','7000','4000']

In [12]:
student_df

,student_id,student_name,course,final_test_marks,course_fee,paid_fee,r_fees
0,S001,Aarav Patil,Data Science,34,50000,25000,25000
1,S002,Vivaan Sharma,Data Analytics,23,40000,24000,16000
3,S004,Arjun Jadhav,Testing,51,20000,16000,4000
4,S005,Sai Pawar,Data Science,48,50000,45000,5000
5,S006,Atharva Kulkarni,Data Analytics,37,40000,16000,24000
...,...,...,...,...,...,...,...
97,S098,Aniket Mehta,Data Analytics,38,40000,24000,16000
98,S099,Nikhil Agrawal,Web Development,53,30000,21000,9000
99,S100,Ruturaj Thakur,Testing,37,20000,16000,4000
100,s101,Sakshi Jagatp,nagpur,DA,56,7000,4000
101,s101,Sakshi Jagatp,nagpur,DA,56,7000,4000