In [1]:
import pandas as pd

In [2]:
student_df = pd.read_csv('student_data.csv')
student_df

,student_id,student_name,branch,course,final_test_marks,course_fee,paid_fee
0,S001,Aarav Patil,Karve Nagar,Data Science,34,50000,25000
1,S002,Vivaan Sharma,Nagpur,Data Analytics,23,40000,24000
2,S003,Aditya Verma,Deccan,Web Development,55,30000,21000
3,S004,Arjun Jadhav,Chinchwad,Testing,51,20000,16000
4,S005,Sai Pawar,Karve Nagar,Data Science,48,50000,45000
...,...,...,...,...,...,...,...
95,S096,Shubham Nair,Chinchwad,Testing,70,20000,8000
96,S097,Yash Singh,Karve Nagar,Data Science,78,50000,25000
97,S098,Aniket Mehta,Nagpur,Data Analytics,38,40000,24000
98,S099,Nikhil Agrawal,Deccan,Web Development,53,30000,21000
99,S100,Ruturaj Thakur,Chinchwad,Testing,37,20000,16000

In [3]:
# filter
student_df['branch'] == 'karve nagar'

0     False
1     False
2     False
3     False
4     False
      ...
95    False
96    False
97    False
98    False
99    False
Name: branch, Length: 100, dtype: bool

In [4]:
student_df[student_df['final_test_marks']>80]

,student_id,student_name,branch,course,final_test_marks,course_fee,paid_fee
7,S008,Rohan Shinde,Chinchwad,Testing,89,20000,12000
9,S010,Kunal Joshi,Nagpur,Data Analytics,95,40000,32000
16,S017,Yash Singh,Karve Nagar,Data Science,84,50000,45000
17,S018,Aniket Mehta,Nagpur,Data Analytics,97,40000,16000
19,S020,Ruturaj Thakur,Chinchwad,Testing,91,20000,12000
21,S022,Pooja Sharma,Nagpur,Data Analytics,89,40000,32000
25,S026,Anushka Kulkarni,Nagpur,Data Analytics,95,40000,24000
41,S042,Vivaan Sharma,Nagpur,Data Analytics,97,40000,16000
45,S046,Atharva Kulkarni,Nagpur,Data Analytics,88,40000,32000
49,S050,Kunal Joshi,Nagpur,Data Analytics,90,40000,24000
51,S052,Pranav Yadav,Chinchwad,Testing,99,20000,16000
53,S054,Akash Kadam,Nagpur,Data Analytics,93,40000,16000
72,S073,Isha Mane,Karve Nagar,Data Science,97,50000,25000
74,S075,Prachi Chavan,Deccan,Web Development,88,30000,21000
80,S081,Aarav Patil,Karve Nagar,Data Science,91,50000,35000
91,S092,Pranav Yadav,Chinchwad,Testing,92,20000,12000
94,S095,Abhishek Chavan,Deccan,Web Development,83,30000,27000

In [6]:
student_df[student_df['course'] == 'Data Analytics']

,student_id,student_name,branch,course,final_test_marks,course_fee,paid_fee
1,S002,Vivaan Sharma,Nagpur,Data Analytics,23,40000,24000
5,S006,Atharva Kulkarni,Nagpur,Data Analytics,37,40000,16000
9,S010,Kunal Joshi,Nagpur,Data Analytics,95,40000,32000
13,S014,Akash Kadam,Nagpur,Data Analytics,31,40000,24000
17,S018,Aniket Mehta,Nagpur,Data Analytics,97,40000,16000
21,S022,Pooja Sharma,Nagpur,Data Analytics,89,40000,32000
25,S026,Anushka Kulkarni,Nagpur,Data Analytics,95,40000,24000
29,S030,Sakshi Joshi,Nagpur,Data Analytics,74,40000,16000
33,S034,Komal Kadam,Nagpur,Data Analytics,47,40000,32000
37,S038,Swati Mehta,Nagpur,Data Analytics,68,40000,24000
41,S042,Vivaan Sharma,Nagpur,Data Analytics,97,40000,16000
45,S046,Atharva Kulkarni,Nagpur,Data Analytics,88,40000,32000
49,S050,Kunal Joshi,Nagpur,Data Analytics,90,40000,24000
53,S054,Akash Kadam,Nagpur,Data Analytics,93,40000,16000
57,S058,Aniket Mehta,Nagpur,Data Analytics,49,40000,32000
61,S062,Pooja Sharma,Nagpur,Data Analytics,32,40000,24000
65,S066,Anushka Kulkarni,Nagpur,Data Analytics,66,40000,16000
69,S070,Sakshi Joshi,Nagpur,Data Analytics,46,40000,32000
73,S074,Komal Kadam,Nagpur,Data Analytics,41,40000,24000
77,S078,Swati Mehta,Nagpur,Data Analytics,79,40000,16000
81,S082,Vivaan Sharma,Nagpur,Data Analytics,48,40000,32000
85,S086,Atharva Kulkarni,Nagpur,Data Analytics,24,40000,24000
89,S090,Kunal Joshi,Nagpur,Data Analytics,28,40000,16000
93,S094,Akash Kadam,Nagpur,Data Analytics,47,40000,32000
97,S098,Aniket Mehta,Nagpur,Data Analytics,38,40000,24000

In [8]:
student_df[(student_df['course'] == 'Data Science') & (student_df['paid_fee'] < 30000)]

,student_id,student_name,branch,course,final_test_marks,course_fee,paid_fee
0,S001,Aarav Patil,Karve Nagar,Data Science,34,50000,25000
12,S013,Saurabh Mane,Karve Nagar,Data Science,23,50000,25000
24,S025,Neha Pawar,Karve Nagar,Data Science,77,50000,25000
36,S037,Tejaswini Singh,Karve Nagar,Data Science,31,50000,25000
48,S049,Rahul More,Karve Nagar,Data Science,30,50000,25000
60,S061,Sneha Patil,Karve Nagar,Data Science,49,50000,25000
72,S073,Isha Mane,Karve Nagar,Data Science,97,50000,25000
84,S085,Sai Pawar,Karve Nagar,Data Science,49,50000,25000
96,S097,Yash Singh,Karve Nagar,Data Science,78,50000,25000

In [10]:
student_df[(student_df['branch'] == 'Karve Nagar') & (student_df['final_test_marks']>80)]

,student_id,student_name,branch,course,final_test_marks,course_fee,paid_fee
16,S017,Yash Singh,Karve Nagar,Data Science,84,50000,45000
72,S073,Isha Mane,Karve Nagar,Data Science,97,50000,25000
80,S081,Aarav Patil,Karve Nagar,Data Science,91,50000,35000

In [14]:
student_df[(student_df['course'] == 'Data Science') | (student_df['course'] == 'Data Analystics')]

,student_id,student_name,branch,course,final_test_marks,course_fee,paid_fee
0,S001,Aarav Patil,Karve Nagar,Data Science,34,50000,25000
4,S005,Sai Pawar,Karve Nagar,Data Science,48,50000,45000
8,S009,Rahul More,Karve Nagar,Data Science,31,50000,35000
12,S013,Saurabh Mane,Karve Nagar,Data Science,23,50000,25000
16,S017,Yash Singh,Karve Nagar,Data Science,84,50000,45000
20,S021,Sneha Patil,Karve Nagar,Data Science,45,50000,35000
24,S025,Neha Pawar,Karve Nagar,Data Science,77,50000,25000
28,S029,Riya More,Karve Nagar,Data Science,40,50000,45000
32,S033,Isha Mane,Karve Nagar,Data Science,39,50000,35000
36,S037,Tejaswini Singh,Karve Nagar,Data Science,31,50000,25000
40,S041,Aarav Patil,Karve Nagar,Data Science,64,50000,45000
44,S045,Sai Pawar,Karve Nagar,Data Science,78,50000,35000
48,S049,Rahul More,Karve Nagar,Data Science,30,50000,25000
52,S053,Saurabh Mane,Karve Nagar,Data Science,66,50000,45000
56,S057,Yash Singh,Karve Nagar,Data Science,25,50000,35000
60,S061,Sneha Patil,Karve Nagar,Data Science,49,50000,25000
64,S065,Neha Pawar,Karve Nagar,Data Science,78,50000,45000
68,S069,Riya More,Karve Nagar,Data Science,65,50000,35000
72,S073,Isha Mane,Karve Nagar,Data Science,97,50000,25000
76,S077,Tejaswini Singh,Karve Nagar,Data Science,40,50000,45000
80,S081,Aarav Patil,Karve Nagar,Data Science,91,50000,35000
84,S085,Sai Pawar,Karve Nagar,Data Science,49,50000,25000
88,S089,Rahul More,Karve Nagar,Data Science,54,50000,45000
92,S093,Saurabh Mane,Karve Nagar,Data Science,60,50000,35000
96,S097,Yash Singh,Karve Nagar,Data Science,78,50000,25000

In [15]:
# merge operations
detail = pd.read_csv('course.csv')
marks = pd.read_csv('test.csv')

In [16]:
detail

   roll            name           course
0     1     Aarav Patil     Data Science
1     2    Priya Sharma   Data Analytics
2     3    Rahul Jadhav  Web Development
3     4     Sneha Pawar          Testing
4     5     Aditya More     Data Science
5     6   Neha Kulkarni   Data Analytics
6     7  Rohan Deshmukh  Web Development
7     8  Anushka Shinde          Testing
8     9     Kunal Patil     Data Science
9    10    Sakshi Joshi   Data Analytics

In [17]:
marks

   roll  test1  test2  test3
0     1     78     82     85
1     2     65     70     68
2     3     88     91     86
3     4     72     75     79
4     5     95     93     97
5     6     81     84     80
6     7     69     73     71

In [18]:
pd.merge(detail,marks,how="inner",on="roll")

   roll            name           course  test1  test2  test3
0     1     Aarav Patil     Data Science     78     82     85
1     2    Priya Sharma   Data Analytics     65     70     68
2     3    Rahul Jadhav  Web Development     88     91     86
3     4     Sneha Pawar          Testing     72     75     79
4     5     Aditya More     Data Science     95     93     97
5     6   Neha Kulkarni   Data Analytics     81     84     80
6     7  Rohan Deshmukh  Web Development     69     73     71

In [21]:
pd.merge(detail,marks,how="left",on="roll")

   roll            name           course  test1  test2  test3
0     1     Aarav Patil     Data Science   78.0   82.0   85.0
1     2    Priya Sharma   Data Analytics   65.0   70.0   68.0
2     3    Rahul Jadhav  Web Development   88.0   91.0   86.0
3     4     Sneha Pawar          Testing   72.0   75.0   79.0
4     5     Aditya More     Data Science   95.0   93.0   97.0
5     6   Neha Kulkarni   Data Analytics   81.0   84.0   80.0
6     7  Rohan Deshmukh  Web Development   69.0   73.0   71.0
7     8  Anushka Shinde          Testing    NaN    NaN    NaN
8     9     Kunal Patil     Data Science    NaN    NaN    NaN
9    10    Sakshi Joshi   Data Analytics    NaN    NaN    NaN

In [20]:
pd.merge(detail,marks,how="right",on="roll")

   roll            name           course  test1  test2  test3
0     1     Aarav Patil     Data Science     78     82     85
1     2    Priya Sharma   Data Analytics     65     70     68
2     3    Rahul Jadhav  Web Development     88     91     86
3     4     Sneha Pawar          Testing     72     75     79
4     5     Aditya More     Data Science     95     93     97
5     6   Neha Kulkarni   Data Analytics     81     84     80
6     7  Rohan Deshmukh  Web Development     69     73     71

In [22]:
pd.merge(detail,marks,how="outer",on="roll")

   roll            name           course  test1  test2  test3
0     1     Aarav Patil     Data Science   78.0   82.0   85.0
1     2    Priya Sharma   Data Analytics   65.0   70.0   68.0
2     3    Rahul Jadhav  Web Development   88.0   91.0   86.0
3     4     Sneha Pawar          Testing   72.0   75.0   79.0
4     5     Aditya More     Data Science   95.0   93.0   97.0
5     6   Neha Kulkarni   Data Analytics   81.0   84.0   80.0
6     7  Rohan Deshmukh  Web Development   69.0   73.0   71.0
7     8  Anushka Shinde          Testing    NaN    NaN    NaN
8     9     Kunal Patil     Data Science    NaN    NaN    NaN
9    10    Sakshi Joshi   Data Analytics    NaN    NaN    NaN