In [1]:
import pandas as pd

In [2]:
emp_df = pd.read_csv('empdata.csv')
emp_df

,emp_id,emp_name,department,city,experience,salary,rating,gender
0,101,Amit Sharma,IT,Pune,3.0,45000.0,4.5,Male
1,102,Priya Patil,HR,Mumbai,5.0,55000.0,4.2,Female
2,103,Rahul Verma,Sales,Nagpur,2.0,35000.0,3.8,Male
3,104,Sneha Joshi,IT,Pune,4.0,50000.0,4.1,Female
4,105,Vikas Kumar,Finance,Mumbai,6.0,65000.0,4.7,Male
5,106,Anjali Singh,Sales,NaN,3.0,40000.0,3.9,Female
6,107,Rohan Deshmukh,IT,Pune,NaN,48000.0,4.3,Male
7,108,Neha Kulkarni,HR,Nashik,5.0,NaN,4.0,Female
8,109,Sachin Patil,Sales,Nagpur,2.0,36000.0,NaN,Male
9,110,Pooja Shah,Finance,Mumbai,7.0,70000.0,4.8,Female
10,111,Amit Sharma,IT,Pune,3.0,45000.0,4.5,Male
11,112,Karan Mehta,IT,Pune,4.0,52000.0,5.0,Male
12,113,Meera Jain,HR,Nashik,5.0,56000.0,4.1,Female
13,114,Akash Gupta,Sales,Nagpur,2.0,34000.0,3.5,Male
14,115,Divya Patil,Finance,Pune,8.0,75000.0,4.9,Female
15,116,Rajesh More,IT,Pune,1.0,30000.0,3.6,Male
16,117,Kavita Singh,HR,Mumbai,4.0,50000.0,3.0,Female
17,118,Manoj Kale,Sales,Nagpur,3.0,41000.0,4.0,Male
18,119,Ritu Sharma,Finance,NaN,6.0,68000.0,4.6,Female
19,120,Sandeep Patil,IT,Pune,5.0,58000.0,4.4,Male
20,120,Sandeep Patil,IT,Pune,5.0,58000.0,4.4,Male
21,120,Sandeep Patil,IT,Pune,5.0,58000.0,4.4,Male

In [6]:
emp_df.isnull()

    emp_id  emp_name  department   city  experience  salary  rating  gender
0    False     False       False  False       False   False   False   False
1    False     False       False  False       False   False   False   False
2    False     False       False  False       False   False   False   False
3    False     False       False  False       False   False   False   False
4    False     False       False  False       False   False   False   False
5    False     False       False   True       False   False   False   False
6    False     False       False  False        True   False   False   False
7    False     False       False  False       False    True   False   False
8    False     False       False  False       False   False   False   False
9    False     False       False  False       False   False   False   False
10   False     False       False  False       False   False   False   False
11   False     False       False  False       False   False   False   False
12   False     False       False  False       False   False   False   False
13   False     False       False  False       False   False   False   False
14   False     False       False  False       False   False   False   False
15   False     False       False  False       False   False   False   False
16   False     False       False  False       False   False   False   False
17   False     False       False  False       False   False   False   False
18   False     False       False   True       False   False   False   False
19   False     False       False  False       False   False   False   False
20   False     False       False  False       False   False   False   False
21   False     False       False  False       False   False   False   False

In [3]:
emp_df.isnull().sum()

emp_id        0
emp_name      0
department    0
city          2
experience    1
salary        1
rating        1
gender        0
dtype: int64

In [4]:
emp = emp_df.dropna()
emp

,emp_id,emp_name,department,city,experience,salary,rating,gender
0,101,Amit Sharma,IT,Pune,3.0,45000.0,4.5,Male
1,102,Priya Patil,HR,Mumbai,5.0,55000.0,4.2,Female
2,103,Rahul Verma,Sales,Nagpur,2.0,35000.0,3.8,Male
3,104,Sneha Joshi,IT,Pune,4.0,50000.0,4.1,Female
4,105,Vikas Kumar,Finance,Mumbai,6.0,65000.0,4.7,Male
9,110,Pooja Shah,Finance,Mumbai,7.0,70000.0,4.8,Female
10,111,Amit Sharma,IT,Pune,3.0,45000.0,4.5,Male
11,112,Karan Mehta,IT,Pune,4.0,52000.0,5.0,Male
12,113,Meera Jain,HR,Nashik,5.0,56000.0,4.1,Female
13,114,Akash Gupta,Sales,Nagpur,2.0,34000.0,3.5,Male
14,115,Divya Patil,Finance,Pune,8.0,75000.0,4.9,Female
15,116,Rajesh More,IT,Pune,1.0,30000.0,3.6,Male
16,117,Kavita Singh,HR,Mumbai,4.0,50000.0,3.0,Female
17,118,Manoj Kale,Sales,Nagpur,3.0,41000.0,4.0,Male
19,120,Sandeep Patil,IT,Pune,5.0,58000.0,4.4,Male
20,120,Sandeep Patil,IT,Pune,5.0,58000.0,4.4,Male
21,120,Sandeep Patil,IT,Pune,5.0,58000.0,4.4,Male

In [5]:
emp_df['rating'] = emp_df['rating'].fillna(0)
emp_df

,emp_id,emp_name,department,city,experience,salary,rating,gender
0,101,Amit Sharma,IT,Pune,3.0,45000.0,4.5,Male
1,102,Priya Patil,HR,Mumbai,5.0,55000.0,4.2,Female
2,103,Rahul Verma,Sales,Nagpur,2.0,35000.0,3.8,Male
3,104,Sneha Joshi,IT,Pune,4.0,50000.0,4.1,Female
4,105,Vikas Kumar,Finance,Mumbai,6.0,65000.0,4.7,Male
5,106,Anjali Singh,Sales,NaN,3.0,40000.0,3.9,Female
6,107,Rohan Deshmukh,IT,Pune,NaN,48000.0,4.3,Male
7,108,Neha Kulkarni,HR,Nashik,5.0,NaN,4.0,Female
8,109,Sachin Patil,Sales,Nagpur,2.0,36000.0,0.0,Male
9,110,Pooja Shah,Finance,Mumbai,7.0,70000.0,4.8,Female
10,111,Amit Sharma,IT,Pune,3.0,45000.0,4.5,Male
11,112,Karan Mehta,IT,Pune,4.0,52000.0,5.0,Male
12,113,Meera Jain,HR,Nashik,5.0,56000.0,4.1,Female
13,114,Akash Gupta,Sales,Nagpur,2.0,34000.0,3.5,Male
14,115,Divya Patil,Finance,Pune,8.0,75000.0,4.9,Female
15,116,Rajesh More,IT,Pune,1.0,30000.0,3.6,Male
16,117,Kavita Singh,HR,Mumbai,4.0,50000.0,3.0,Female
17,118,Manoj Kale,Sales,Nagpur,3.0,41000.0,4.0,Male
18,119,Ritu Sharma,Finance,NaN,6.0,68000.0,4.6,Female
19,120,Sandeep Patil,IT,Pune,5.0,58000.0,4.4,Male
20,120,Sandeep Patil,IT,Pune,5.0,58000.0,4.4,Male
21,120,Sandeep Patil,IT,Pune,5.0,58000.0,4.4,Male

In [8]:
emp_df['city'].ffill()

0       Pune
1     Mumbai
2     Nagpur
3       Pune
4     Mumbai
5     Mumbai
6       Pune
7     Nashik
8     Nagpur
9     Mumbai
10      Pune
11      Pune
12    Nashik
13    Nagpur
14      Pune
15      Pune
16    Mumbai
17    Nagpur
18    Nagpur
19      Pune
20      Pune
21      Pune
Name: city, dtype: object

In [9]:
emp_df['city'].bfill()

0       Pune
1     Mumbai
2     Nagpur
3       Pune
4     Mumbai
5       Pune
6       Pune
7     Nashik
8     Nagpur
9     Mumbai
10      Pune
11      Pune
12    Nashik
13    Nagpur
14      Pune
15      Pune
16    Mumbai
17    Nagpur
18      Pune
19      Pune
20      Pune
21      Pune
Name: city, dtype: object

In [11]:
emp_df.dropna()

,emp_id,emp_name,department,city,experience,salary,rating,gender
0,101,Amit Sharma,IT,Pune,3.0,45000.0,4.5,Male
1,102,Priya Patil,HR,Mumbai,5.0,55000.0,4.2,Female
2,103,Rahul Verma,Sales,Nagpur,2.0,35000.0,3.8,Male
3,104,Sneha Joshi,IT,Pune,4.0,50000.0,4.1,Female
4,105,Vikas Kumar,Finance,Mumbai,6.0,65000.0,4.7,Male
8,109,Sachin Patil,Sales,Nagpur,2.0,36000.0,0.0,Male
9,110,Pooja Shah,Finance,Mumbai,7.0,70000.0,4.8,Female
10,111,Amit Sharma,IT,Pune,3.0,45000.0,4.5,Male
11,112,Karan Mehta,IT,Pune,4.0,52000.0,5.0,Male
12,113,Meera Jain,HR,Nashik,5.0,56000.0,4.1,Female
13,114,Akash Gupta,Sales,Nagpur,2.0,34000.0,3.5,Male
14,115,Divya Patil,Finance,Pune,8.0,75000.0,4.9,Female
15,116,Rajesh More,IT,Pune,1.0,30000.0,3.6,Male
16,117,Kavita Singh,HR,Mumbai,4.0,50000.0,3.0,Female
17,118,Manoj Kale,Sales,Nagpur,3.0,41000.0,4.0,Male
19,120,Sandeep Patil,IT,Pune,5.0,58000.0,4.4,Male
20,120,Sandeep Patil,IT,Pune,5.0,58000.0,4.4,Male
21,120,Sandeep Patil,IT,Pune,5.0,58000.0,4.4,Male

In [10]:
def perf(rating):
    if rating>4:
        return "Excellent"
    else:
        return "Good"

In [13]:
emp_df['performance'] = emp['rating'].apply(perf)
emp_df

,emp_id,emp_name,department,city,experience,salary,rating,gender,performance
0,101,Amit Sharma,IT,Pune,3.0,45000.0,4.5,Male,Excellent
1,102,Priya Patil,HR,Mumbai,5.0,55000.0,4.2,Female,Excellent
2,103,Rahul Verma,Sales,Nagpur,2.0,35000.0,3.8,Male,Good
3,104,Sneha Joshi,IT,Pune,4.0,50000.0,4.1,Female,Excellent
4,105,Vikas Kumar,Finance,Mumbai,6.0,65000.0,4.7,Male,Excellent
5,106,Anjali Singh,Sales,NaN,3.0,40000.0,3.9,Female,NaN
6,107,Rohan Deshmukh,IT,Pune,NaN,48000.0,4.3,Male,NaN
7,108,Neha Kulkarni,HR,Nashik,5.0,NaN,4.0,Female,NaN
8,109,Sachin Patil,Sales,Nagpur,2.0,36000.0,0.0,Male,NaN
9,110,Pooja Shah,Finance,Mumbai,7.0,70000.0,4.8,Female,Excellent
10,111,Amit Sharma,IT,Pune,3.0,45000.0,4.5,Male,Excellent
11,112,Karan Mehta,IT,Pune,4.0,52000.0,5.0,Male,Excellent
12,113,Meera Jain,HR,Nashik,5.0,56000.0,4.1,Female,Excellent
13,114,Akash Gupta,Sales,Nagpur,2.0,34000.0,3.5,Male,Good
14,115,Divya Patil,Finance,Pune,8.0,75000.0,4.9,Female,Excellent
15,116,Rajesh More,IT,Pune,1.0,30000.0,3.6,Male,Good
16,117,Kavita Singh,HR,Mumbai,4.0,50000.0,3.0,Female,Good
17,118,Manoj Kale,Sales,Nagpur,3.0,41000.0,4.0,Male,Good
18,119,Ritu Sharma,Finance,NaN,6.0,68000.0,4.6,Female,NaN
19,120,Sandeep Patil,IT,Pune,5.0,58000.0,4.4,Male,Excellent
20,120,Sandeep Patil,IT,Pune,5.0,58000.0,4.4,Male,Excellent
21,120,Sandeep Patil,IT,Pune,5.0,58000.0,4.4,Male,Excellent

In [14]:
def increment(salary):
    if salary > 50000:
        new_salary = salary + salary*10/100
    elif salary > 40000:
        new_salary = salary + salary*15/100
    elif salary > 30000:
        new_salary = salary + salary*20/100
    else:
        new_salary = salary + salary*25/100
    return new_salary

In [15]:
emp_df['salary'] = emp_df['salary'].apply(increment)
emp_df

,emp_id,emp_name,department,city,experience,salary,rating,gender,performance
0,101,Amit Sharma,IT,Pune,3.0,51750.0,4.5,Male,Excellent
1,102,Priya Patil,HR,Mumbai,5.0,60500.0,4.2,Female,Excellent
2,103,Rahul Verma,Sales,Nagpur,2.0,42000.0,3.8,Male,Good
3,104,Sneha Joshi,IT,Pune,4.0,57500.0,4.1,Female,Excellent
4,105,Vikas Kumar,Finance,Mumbai,6.0,71500.0,4.7,Male,Excellent
5,106,Anjali Singh,Sales,NaN,3.0,48000.0,3.9,Female,NaN
6,107,Rohan Deshmukh,IT,Pune,NaN,55200.0,4.3,Male,NaN
7,108,Neha Kulkarni,HR,Nashik,5.0,NaN,4.0,Female,NaN
8,109,Sachin Patil,Sales,Nagpur,2.0,43200.0,0.0,Male,NaN
9,110,Pooja Shah,Finance,Mumbai,7.0,77000.0,4.8,Female,Excellent
10,111,Amit Sharma,IT,Pune,3.0,51750.0,4.5,Male,Excellent
11,112,Karan Mehta,IT,Pune,4.0,57200.0,5.0,Male,Excellent
12,113,Meera Jain,HR,Nashik,5.0,61600.0,4.1,Female,Excellent
13,114,Akash Gupta,Sales,Nagpur,2.0,40800.0,3.5,Male,Good
14,115,Divya Patil,Finance,Pune,8.0,82500.0,4.9,Female,Excellent
15,116,Rajesh More,IT,Pune,1.0,37500.0,3.6,Male,Good
16,117,Kavita Singh,HR,Mumbai,4.0,57500.0,3.0,Female,Good
17,118,Manoj Kale,Sales,Nagpur,3.0,47150.0,4.0,Male,Good
18,119,Ritu Sharma,Finance,NaN,6.0,74800.0,4.6,Female,NaN
19,120,Sandeep Patil,IT,Pune,5.0,63800.0,4.4,Male,Excellent
20,120,Sandeep Patil,IT,Pune,5.0,63800.0,4.4,Male,Excellent
21,120,Sandeep Patil,IT,Pune,5.0,63800.0,4.4,Male,Excellent

In [16]:
emp_df['department'].replace("IT",'Operation',inplace=True)
emp_df

,emp_id,emp_name,department,city,experience,salary,rating,gender,performance
0,101,Amit Sharma,Operation,Pune,3.0,51750.0,4.5,Male,Excellent
1,102,Priya Patil,HR,Mumbai,5.0,60500.0,4.2,Female,Excellent
2,103,Rahul Verma,Sales,Nagpur,2.0,42000.0,3.8,Male,Good
3,104,Sneha Joshi,Operation,Pune,4.0,57500.0,4.1,Female,Excellent
4,105,Vikas Kumar,Finance,Mumbai,6.0,71500.0,4.7,Male,Excellent
5,106,Anjali Singh,Sales,NaN,3.0,48000.0,3.9,Female,NaN
6,107,Rohan Deshmukh,Operation,Pune,NaN,55200.0,4.3,Male,NaN
7,108,Neha Kulkarni,HR,Nashik,5.0,NaN,4.0,Female,NaN
8,109,Sachin Patil,Sales,Nagpur,2.0,43200.0,0.0,Male,NaN
9,110,Pooja Shah,Finance,Mumbai,7.0,77000.0,4.8,Female,Excellent
10,111,Amit Sharma,Operation,Pune,3.0,51750.0,4.5,Male,Excellent
11,112,Karan Mehta,Operation,Pune,4.0,57200.0,5.0,Male,Excellent
12,113,Meera Jain,HR,Nashik,5.0,61600.0,4.1,Female,Excellent
13,114,Akash Gupta,Sales,Nagpur,2.0,40800.0,3.5,Male,Good
14,115,Divya Patil,Finance,Pune,8.0,82500.0,4.9,Female,Excellent
15,116,Rajesh More,Operation,Pune,1.0,37500.0,3.6,Male,Good
16,117,Kavita Singh,HR,Mumbai,4.0,57500.0,3.0,Female,Good
17,118,Manoj Kale,Sales,Nagpur,3.0,47150.0,4.0,Male,Good
18,119,Ritu Sharma,Finance,NaN,6.0,74800.0,4.6,Female,NaN
19,120,Sandeep Patil,Operation,Pune,5.0,63800.0,4.4,Male,Excellent
20,120,Sandeep Patil,Operation,Pune,5.0,63800.0,4.4,Male,Excellent
21,120,Sandeep Patil,Operation,Pune,5.0,63800.0,4.4,Male,Excellent

In [18]:
emp_df['salary'].agg(['sum','min','max','mean']).astype(int)

sum     1208850
min       37500
max       82500
mean      57564
Name: salary, dtype: int64

In [20]:
emp_df.duplicated().sum()

np.int64(2)

In [22]:
emp_df.drop_duplicates()

,emp_id,emp_name,department,city,experience,salary,rating,gender,performance
0,101,Amit Sharma,Operation,Pune,3.0,51750.0,4.5,Male,Excellent
1,102,Priya Patil,HR,Mumbai,5.0,60500.0,4.2,Female,Excellent
2,103,Rahul Verma,Sales,Nagpur,2.0,42000.0,3.8,Male,Good
3,104,Sneha Joshi,Operation,Pune,4.0,57500.0,4.1,Female,Excellent
4,105,Vikas Kumar,Finance,Mumbai,6.0,71500.0,4.7,Male,Excellent
5,106,Anjali Singh,Sales,NaN,3.0,48000.0,3.9,Female,NaN
6,107,Rohan Deshmukh,Operation,Pune,NaN,55200.0,4.3,Male,NaN
7,108,Neha Kulkarni,HR,Nashik,5.0,NaN,4.0,Female,NaN
8,109,Sachin Patil,Sales,Nagpur,2.0,43200.0,0.0,Male,NaN
9,110,Pooja Shah,Finance,Mumbai,7.0,77000.0,4.8,Female,Excellent
10,111,Amit Sharma,Operation,Pune,3.0,51750.0,4.5,Male,Excellent
11,112,Karan Mehta,Operation,Pune,4.0,57200.0,5.0,Male,Excellent
12,113,Meera Jain,HR,Nashik,5.0,61600.0,4.1,Female,Excellent
13,114,Akash Gupta,Sales,Nagpur,2.0,40800.0,3.5,Male,Good
14,115,Divya Patil,Finance,Pune,8.0,82500.0,4.9,Female,Excellent
15,116,Rajesh More,Operation,Pune,1.0,37500.0,3.6,Male,Good
16,117,Kavita Singh,HR,Mumbai,4.0,57500.0,3.0,Female,Good
17,118,Manoj Kale,Sales,Nagpur,3.0,47150.0,4.0,Male,Good
18,119,Ritu Sharma,Finance,NaN,6.0,74800.0,4.6,Female,NaN
19,120,Sandeep Patil,Operation,Pune,5.0,63800.0,4.4,Male,Excellent